// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: admin.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPlatformSpendStats = `-- name: GetPlatformSpendStats :one
SELECT COALESCE(SUM(credit_spent), 0)::numeric AS total_lifetime_credit_spend,
	COALESCE(SUM(total_dollars), 0)::numeric AS total_lifetime_dollar_spend
FROM orders
`

type GetPlatformSpendStatsRow struct {
	TotalLifetimeCreditSpend pgtype.Numeric
	TotalLifetimeDollarSpend pgtype.Numeric
}

func (q *Queries) GetPlatformSpendStats(ctx context.Context) (GetPlatformSpendStatsRow, error) {
	row := q.db.QueryRow(ctx, getPlatformSpendStats)
	var i GetPlatformSpendStatsRow
	err := row.Scan(&i.TotalLifetimeCreditSpend, &i.TotalLifetimeDollarSpend)
	return i, err
}
