// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: board_types.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countBoardsByType = `-- name: CountBoardsByType :one
SELECT COUNT(*)
FROM boards
WHERE board_type_id = $1
`

func (q *Queries) CountBoardsByType(ctx context.Context, boardTypeID pgtype.Int4) (int64, error) {
	row := q.db.QueryRow(ctx, countBoardsByType, boardTypeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBoardType = `-- name: CreateBoardType :one
INSERT INTO board_types (
		name,
		description,
		dimensions,
		width,
		height,
		hourly_price
	)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id,
	name,
	description,
	dimensions,
	width,
	height,
	hourly_price
`

type CreateBoardTypeParams struct {
	Name        string
	Description pgtype.Text
	Dimensions  pgtype.Text
	Width       int32
	Height      int32
	HourlyPrice int32
}

func (q *Queries) CreateBoardType(ctx context.Context, arg CreateBoardTypeParams) (BoardType, error) {
	row := q.db.QueryRow(ctx, createBoardType,
		arg.Name,
		arg.Description,
		arg.Dimensions,
		arg.Width,
		arg.Height,
		arg.HourlyPrice,
	)
	var i BoardType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Dimensions,
		&i.Width,
		&i.Height,
		&i.HourlyPrice,
	)
	return i, err
}

const deleteBoardType = `-- name: DeleteBoardType :exec
DELETE FROM board_types
WHERE id = $1
`

func (q *Queries) DeleteBoardType(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteBoardType, id)
	return err
}

const getBoardTypeByID = `-- name: GetBoardTypeByID :one
SELECT id,
	name,
	description,
	dimensions,
	width,
	height,
	hourly_price
FROM board_types
WHERE id = $1
`

func (q *Queries) GetBoardTypeByID(ctx context.Context, id int32) (BoardType, error) {
	row := q.db.QueryRow(ctx, getBoardTypeByID, id)
	var i BoardType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Dimensions,
		&i.Width,
		&i.Height,
		&i.HourlyPrice,
	)
	return i, err
}

const listBoardTypes = `-- name: ListBoardTypes :many
SELECT id,
	name,
	description,
	dimensions,
	width,
	height,
	hourly_price
FROM board_types
ORDER BY name
`

func (q *Queries) ListBoardTypes(ctx context.Context) ([]BoardType, error) {
	rows, err := q.db.Query(ctx, listBoardTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BoardType
	for rows.Next() {
		var i BoardType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Dimensions,
			&i.Width,
			&i.Height,
			&i.HourlyPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBoardType = `-- name: UpdateBoardType :one
UPDATE board_types
SET name = COALESCE($2, name),
	description = COALESCE($3, description),
	dimensions = COALESCE($4, dimensions),
	width = COALESCE($5, width),
	height = COALESCE($6, height),
	hourly_price = COALESCE($7, hourly_price)
WHERE id = $1
RETURNING id,
	name,
	description,
	dimensions,
	width,
	height,
	hourly_price
`

type UpdateBoardTypeParams struct {
	ID          int32
	Name        string
	Description pgtype.Text
	Dimensions  pgtype.Text
	Width       int32
	Height      int32
	HourlyPrice int32
}

func (q *Queries) UpdateBoardType(ctx context.Context, arg UpdateBoardTypeParams) (BoardType, error) {
	row := q.db.QueryRow(ctx, updateBoardType,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Dimensions,
		arg.Width,
		arg.Height,
		arg.HourlyPrice,
	)
	var i BoardType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Dimensions,
		&i.Width,
		&i.Height,
		&i.HourlyPrice,
	)
	return i, err
}
