// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: boards.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignBoardToHost = `-- name: AssignBoardToHost :one
UPDATE boards
SET owner_id = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, board_type_id, owner_id, device_id, approved, location, created_at, updated_at, last_sync_at, last_known_latitude, last_known_longitude, current_geo_zone, device_status, manifest_version
`

type AssignBoardToHostParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

func (q *Queries) AssignBoardToHost(ctx context.Context, arg AssignBoardToHostParams) (Board, error) {
	row := q.db.QueryRow(ctx, assignBoardToHost, arg.ID, arg.OwnerID)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.BoardTypeID,
		&i.OwnerID,
		&i.DeviceID,
		&i.Approved,
		&i.Location,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSyncAt,
		&i.LastKnownLatitude,
		&i.LastKnownLongitude,
		&i.CurrentGeoZone,
		&i.DeviceStatus,
		&i.ManifestVersion,
	)
	return i, err
}

const clearBoardPrimaryMedia = `-- name: ClearBoardPrimaryMedia :exec
UPDATE board_media
SET is_primary = false
WHERE board_id = $1
`

func (q *Queries) ClearBoardPrimaryMedia(ctx context.Context, boardID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearBoardPrimaryMedia, boardID)
	return err
}

const createBoard = `-- name: CreateBoard :one
INSERT INTO boards (
        board_type_id,
        owner_id,
        device_id,
        approved,
        location
    )
VALUES ($1, $2, $3, $4, $5)
RETURNING id, board_type_id, owner_id, device_id, approved, location, created_at, updated_at, last_sync_at, last_known_latitude, last_known_longitude, current_geo_zone, device_status, manifest_version
`

type CreateBoardParams struct {
	BoardTypeID pgtype.Int4
	OwnerID     pgtype.UUID
	DeviceID    pgtype.Text
	Approved    pgtype.Bool
	Location    pgtype.Text
}

func (q *Queries) CreateBoard(ctx context.Context, arg CreateBoardParams) (Board, error) {
	row := q.db.QueryRow(ctx, createBoard,
		arg.BoardTypeID,
		arg.OwnerID,
		arg.DeviceID,
		arg.Approved,
		arg.Location,
	)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.BoardTypeID,
		&i.OwnerID,
		&i.DeviceID,
		&i.Approved,
		&i.Location,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSyncAt,
		&i.LastKnownLatitude,
		&i.LastKnownLongitude,
		&i.CurrentGeoZone,
		&i.DeviceStatus,
		&i.ManifestVersion,
	)
	return i, err
}

const createBoardMedia = `-- name: CreateBoardMedia :one
INSERT INTO board_media (
        board_id,
        url,
        type,
        caption,
        is_primary,
        sort_order
    )
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, board_id, url, type, caption, is_primary, sort_order, created_at
`

type CreateBoardMediaParams struct {
	BoardID   pgtype.UUID
	Url       string
	Type      MediaType
	Caption   pgtype.Text
	IsPrimary pgtype.Bool
	SortOrder pgtype.Int4
}

func (q *Queries) CreateBoardMedia(ctx context.Context, arg CreateBoardMediaParams) (BoardMedium, error) {
	row := q.db.QueryRow(ctx, createBoardMedia,
		arg.BoardID,
		arg.Url,
		arg.Type,
		arg.Caption,
		arg.IsPrimary,
		arg.SortOrder,
	)
	var i BoardMedium
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Url,
		&i.Type,
		&i.Caption,
		&i.IsPrimary,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBoard = `-- name: DeleteBoard :exec
DELETE FROM boards
WHERE id = $1
`

func (q *Queries) DeleteBoard(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBoard, id)
	return err
}

const deleteBoardMedia = `-- name: DeleteBoardMedia :exec
DELETE FROM board_media
WHERE id = $1
`

func (q *Queries) DeleteBoardMedia(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBoardMedia, id)
	return err
}

const getBoard = `-- name: GetBoard :one
SELECT id, board_type_id, owner_id, device_id, approved, location, created_at, updated_at, last_sync_at, last_known_latitude, last_known_longitude, current_geo_zone, device_status, manifest_version FROM boards WHERE id = $1
`

func (q *Queries) GetBoard(ctx context.Context, id pgtype.UUID) (Board, error) {
	row := q.db.QueryRow(ctx, getBoard, id)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.BoardTypeID,
		&i.OwnerID,
		&i.DeviceID,
		&i.Approved,
		&i.Location,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSyncAt,
		&i.LastKnownLatitude,
		&i.LastKnownLongitude,
		&i.CurrentGeoZone,
		&i.DeviceStatus,
		&i.ManifestVersion,
	)
	return i, err
}

const getBoardByDeviceID = `-- name: GetBoardByDeviceID :one
SELECT b.id,
    b.board_type_id,
    b.owner_id,
    b.device_id,
    b.approved,
    b.location,
    b.created_at,
    b.updated_at,
    b.last_sync_at,
    b.last_known_latitude,
    b.last_known_longitude,
    b.current_geo_zone,
    b.device_status,
    b.manifest_version
FROM boards b
WHERE b.device_id = $1
`

func (q *Queries) GetBoardByDeviceID(ctx context.Context, deviceID pgtype.Text) (Board, error) {
	row := q.db.QueryRow(ctx, getBoardByDeviceID, deviceID)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.BoardTypeID,
		&i.OwnerID,
		&i.DeviceID,
		&i.Approved,
		&i.Location,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSyncAt,
		&i.LastKnownLatitude,
		&i.LastKnownLongitude,
		&i.CurrentGeoZone,
		&i.DeviceStatus,
		&i.ManifestVersion,
	)
	return i, err
}

const getBoardByID = `-- name: GetBoardByID :one
SELECT b.id,
    b.board_type_id,
    b.owner_id,
    b.device_id,
    b.approved,
    b.location,
    b.created_at,
    b.updated_at,
    bt.name as board_type_name,
    u.name as owner_name,
    u.email as owner_email
FROM boards b
    LEFT JOIN board_types bt ON b.board_type_id = bt.id
    LEFT JOIN users u ON b.owner_id = u.id
WHERE b.id = $1
`

type GetBoardByIDRow struct {
	ID            pgtype.UUID
	BoardTypeID   pgtype.Int4
	OwnerID       pgtype.UUID
	DeviceID      pgtype.Text
	Approved      pgtype.Bool
	Location      pgtype.Text
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	BoardTypeName pgtype.Text
	OwnerName     pgtype.Text
	OwnerEmail    pgtype.Text
}

func (q *Queries) GetBoardByID(ctx context.Context, id pgtype.UUID) (GetBoardByIDRow, error) {
	row := q.db.QueryRow(ctx, getBoardByID, id)
	var i GetBoardByIDRow
	err := row.Scan(
		&i.ID,
		&i.BoardTypeID,
		&i.OwnerID,
		&i.DeviceID,
		&i.Approved,
		&i.Location,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BoardTypeName,
		&i.OwnerName,
		&i.OwnerEmail,
	)
	return i, err
}

const getBoardMediaByID = `-- name: GetBoardMediaByID :one
SELECT id,
    board_id,
    url,
    type,
    caption,
    is_primary,
    sort_order,
    created_at
FROM board_media
WHERE id = $1
`

func (q *Queries) GetBoardMediaByID(ctx context.Context, id pgtype.UUID) (BoardMedium, error) {
	row := q.db.QueryRow(ctx, getBoardMediaByID, id)
	var i BoardMedium
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Url,
		&i.Type,
		&i.Caption,
		&i.IsPrimary,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const getBoardWithGeofence = `-- name: GetBoardWithGeofence :one
SELECT
    b.id,
    b.board_type_id,
    b.owner_id,
    b.device_id,
    b.approved,
    b.location,
    b.current_geo_zone,
    b.created_at,
    b.updated_at,
    bt.name as board_type_name,
    bt.width,
    bt.height,
    true as is_active
FROM boards b
LEFT JOIN board_types bt ON b.board_type_id = bt.id
WHERE b.id = $1 AND b.approved = true
`

type GetBoardWithGeofenceRow struct {
	ID             pgtype.UUID
	BoardTypeID    pgtype.Int4
	OwnerID        pgtype.UUID
	DeviceID       pgtype.Text
	Approved       pgtype.Bool
	Location       pgtype.Text
	CurrentGeoZone pgtype.Text
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	BoardTypeName  pgtype.Text
	Width          pgtype.Int4
	Height         pgtype.Int4
	IsActive       bool
}

func (q *Queries) GetBoardWithGeofence(ctx context.Context, id pgtype.UUID) (GetBoardWithGeofenceRow, error) {
	row := q.db.QueryRow(ctx, getBoardWithGeofence, id)
	var i GetBoardWithGeofenceRow
	err := row.Scan(
		&i.ID,
		&i.BoardTypeID,
		&i.OwnerID,
		&i.DeviceID,
		&i.Approved,
		&i.Location,
		&i.CurrentGeoZone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BoardTypeName,
		&i.Width,
		&i.Height,
		&i.IsActive,
	)
	return i, err
}

const getBoardsByIDs = `-- name: GetBoardsByIDs :many
SELECT
    b.id,
    b.board_type_id,
    b.owner_id,
    b.device_id,
    b.approved,
    b.location,
    b.current_geo_zone,
    b.created_at,
    b.updated_at,
    bt.name as board_type_name,
    bt.width,
    bt.height,
    true as is_active
FROM boards b
LEFT JOIN board_types bt ON b.board_type_id = bt.id
WHERE b.id = ANY($1::uuid[]) AND b.approved = true
`

type GetBoardsByIDsRow struct {
	ID             pgtype.UUID
	BoardTypeID    pgtype.Int4
	OwnerID        pgtype.UUID
	DeviceID       pgtype.Text
	Approved       pgtype.Bool
	Location       pgtype.Text
	CurrentGeoZone pgtype.Text
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	BoardTypeName  pgtype.Text
	Width          pgtype.Int4
	Height         pgtype.Int4
	IsActive       bool
}

func (q *Queries) GetBoardsByIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]GetBoardsByIDsRow, error) {
	rows, err := q.db.Query(ctx, getBoardsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBoardsByIDsRow
	for rows.Next() {
		var i GetBoardsByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.BoardTypeID,
			&i.OwnerID,
			&i.DeviceID,
			&i.Approved,
			&i.Location,
			&i.CurrentGeoZone,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BoardTypeName,
			&i.Width,
			&i.Height,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPrimaryBoardMedia = `-- name: GetPrimaryBoardMedia :one
SELECT id,
    board_id,
    url,
    type,
    caption,
    is_primary,
    sort_order,
    created_at
FROM board_media
WHERE board_id = $1
    AND is_primary = true
LIMIT 1
`

func (q *Queries) GetPrimaryBoardMedia(ctx context.Context, boardID pgtype.UUID) (BoardMedium, error) {
	row := q.db.QueryRow(ctx, getPrimaryBoardMedia, boardID)
	var i BoardMedium
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Url,
		&i.Type,
		&i.Caption,
		&i.IsPrimary,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const listBoardMedia = `-- name: ListBoardMedia :many
SELECT id,
    board_id,
    url,
    type,
    caption,
    is_primary,
    sort_order,
    created_at
FROM board_media
WHERE board_id = $1
ORDER BY sort_order ASC,
    created_at DESC
`

// Board Media Queries
func (q *Queries) ListBoardMedia(ctx context.Context, boardID pgtype.UUID) ([]BoardMedium, error) {
	rows, err := q.db.Query(ctx, listBoardMedia, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BoardMedium
	for rows.Next() {
		var i BoardMedium
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.Url,
			&i.Type,
			&i.Caption,
			&i.IsPrimary,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBoards = `-- name: ListBoards :many
SELECT b.id,
    b.board_type_id,
    b.owner_id,
    b.device_id,
    b.approved,
    b.location,
    b.created_at,
    b.updated_at,
    bt.name as board_type_name,
    u.name as owner_name,
    u.email as owner_email,
    COUNT(bm.id) as media_count
FROM boards b
    LEFT JOIN board_types bt ON b.board_type_id = bt.id
    LEFT JOIN users u ON b.owner_id = u.id
    LEFT JOIN board_media bm ON b.id = bm.board_id
GROUP BY b.id,
    b.board_type_id,
    b.owner_id,
    b.device_id,
    b.approved,
    b.location,
    b.created_at,
    b.updated_at,
    bt.name,
    u.name,
    u.email
ORDER BY b.created_at DESC
`

type ListBoardsRow struct {
	ID            pgtype.UUID
	BoardTypeID   pgtype.Int4
	OwnerID       pgtype.UUID
	DeviceID      pgtype.Text
	Approved      pgtype.Bool
	Location      pgtype.Text
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	BoardTypeName pgtype.Text
	OwnerName     pgtype.Text
	OwnerEmail    pgtype.Text
	MediaCount    int64
}

func (q *Queries) ListBoards(ctx context.Context) ([]ListBoardsRow, error) {
	rows, err := q.db.Query(ctx, listBoards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBoardsRow
	for rows.Next() {
		var i ListBoardsRow
		if err := rows.Scan(
			&i.ID,
			&i.BoardTypeID,
			&i.OwnerID,
			&i.DeviceID,
			&i.Approved,
			&i.Location,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BoardTypeName,
			&i.OwnerName,
			&i.OwnerEmail,
			&i.MediaCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBoardsByOwner = `-- name: ListBoardsByOwner :many
SELECT b.id,
    b.board_type_id,
    b.owner_id,
    b.device_id,
    b.approved,
    b.location,
    b.created_at,
    b.updated_at,
    bt.name as board_type_name,
    u.name as owner_name,
    u.email as owner_email,
    COUNT(bm.id) as media_count
FROM boards b
    LEFT JOIN board_types bt ON b.board_type_id = bt.id
    LEFT JOIN users u ON b.owner_id = u.id
    LEFT JOIN board_media bm ON b.id = bm.board_id
WHERE b.owner_id = $1
GROUP BY b.id,
    b.board_type_id,
    b.owner_id,
    b.device_id,
    b.approved,
    b.location,
    b.created_at,
    b.updated_at,
    bt.name,
    u.name,
    u.email
ORDER BY b.created_at DESC
`

type ListBoardsByOwnerRow struct {
	ID            pgtype.UUID
	BoardTypeID   pgtype.Int4
	OwnerID       pgtype.UUID
	DeviceID      pgtype.Text
	Approved      pgtype.Bool
	Location      pgtype.Text
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	BoardTypeName pgtype.Text
	OwnerName     pgtype.Text
	OwnerEmail    pgtype.Text
	MediaCount    int64
}

func (q *Queries) ListBoardsByOwner(ctx context.Context, ownerID pgtype.UUID) ([]ListBoardsByOwnerRow, error) {
	rows, err := q.db.Query(ctx, listBoardsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBoardsByOwnerRow
	for rows.Next() {
		var i ListBoardsByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.BoardTypeID,
			&i.OwnerID,
			&i.DeviceID,
			&i.Approved,
			&i.Location,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BoardTypeName,
			&i.OwnerName,
			&i.OwnerEmail,
			&i.MediaCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHosts = `-- name: ListHosts :many
SELECT id,
    name,
    email
FROM users
WHERE role = 'host'
ORDER BY name
`

type ListHostsRow struct {
	ID    pgtype.UUID
	Name  pgtype.Text
	Email string
}

func (q *Queries) ListHosts(ctx context.Context) ([]ListHostsRow, error) {
	rows, err := q.db.Query(ctx, listHosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHostsRow
	for rows.Next() {
		var i ListHostsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBoard = `-- name: UpdateBoard :one
UPDATE boards
SET board_type_id = COALESCE($2, board_type_id),
    owner_id = CASE
        WHEN $3::uuid = '00000000-0000-0000-0000-000000000000'::uuid THEN owner_id -- Don't update (sentinel value)
        ELSE $3::uuid -- Set to NULL (if NULL) or UUID value
    END,
    device_id = COALESCE($4, device_id),
    approved = COALESCE($5, approved),
    location = COALESCE($6, location),
    updated_at = NOW()
WHERE id = $1
RETURNING id, board_type_id, owner_id, device_id, approved, location, created_at, updated_at, last_sync_at, last_known_latitude, last_known_longitude, current_geo_zone, device_status, manifest_version
`

type UpdateBoardParams struct {
	ID          pgtype.UUID
	BoardTypeID pgtype.Int4
	Column3     pgtype.UUID
	DeviceID    pgtype.Text
	Approved    pgtype.Bool
	Location    pgtype.Text
}

func (q *Queries) UpdateBoard(ctx context.Context, arg UpdateBoardParams) (Board, error) {
	row := q.db.QueryRow(ctx, updateBoard,
		arg.ID,
		arg.BoardTypeID,
		arg.Column3,
		arg.DeviceID,
		arg.Approved,
		arg.Location,
	)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.BoardTypeID,
		&i.OwnerID,
		&i.DeviceID,
		&i.Approved,
		&i.Location,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSyncAt,
		&i.LastKnownLatitude,
		&i.LastKnownLongitude,
		&i.CurrentGeoZone,
		&i.DeviceStatus,
		&i.ManifestVersion,
	)
	return i, err
}

const updateBoardMedia = `-- name: UpdateBoardMedia :one
UPDATE board_media
SET caption = COALESCE($2, caption),
    is_primary = COALESCE($3, is_primary),
    sort_order = COALESCE($4, sort_order)
WHERE id = $1
RETURNING id, board_id, url, type, caption, is_primary, sort_order, created_at
`

type UpdateBoardMediaParams struct {
	ID        pgtype.UUID
	Caption   pgtype.Text
	IsPrimary pgtype.Bool
	SortOrder pgtype.Int4
}

func (q *Queries) UpdateBoardMedia(ctx context.Context, arg UpdateBoardMediaParams) (BoardMedium, error) {
	row := q.db.QueryRow(ctx, updateBoardMedia,
		arg.ID,
		arg.Caption,
		arg.IsPrimary,
		arg.SortOrder,
	)
	var i BoardMedium
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Url,
		&i.Type,
		&i.Caption,
		&i.IsPrimary,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}
