// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: daily_board_manifests.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDailyBoardManifest = `-- name: CreateDailyBoardManifest :one
INSERT INTO daily_board_manifests (
    board_id,
    manifest_date,
    compiled_json,
    ad_minute_allocations,
    is_published,
    creative_snapshot
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, board_id, manifest_date, compiled_json, ad_minute_allocations, created_at, updated_at, is_published, creative_snapshot
`

type CreateDailyBoardManifestParams struct {
	BoardID             pgtype.UUID
	ManifestDate        pgtype.Date
	CompiledJson        []byte
	AdMinuteAllocations []byte
	IsPublished         pgtype.Bool
	CreativeSnapshot    []byte
}

func (q *Queries) CreateDailyBoardManifest(ctx context.Context, arg CreateDailyBoardManifestParams) (DailyBoardManifest, error) {
	row := q.db.QueryRow(ctx, createDailyBoardManifest,
		arg.BoardID,
		arg.ManifestDate,
		arg.CompiledJson,
		arg.AdMinuteAllocations,
		arg.IsPublished,
		arg.CreativeSnapshot,
	)
	var i DailyBoardManifest
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.ManifestDate,
		&i.CompiledJson,
		&i.AdMinuteAllocations,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsPublished,
		&i.CreativeSnapshot,
	)
	return i, err
}

const deleteOldManifests = `-- name: DeleteOldManifests :exec
DELETE FROM daily_board_manifests
WHERE manifest_date < CURRENT_DATE - INTERVAL '30 days'
`

func (q *Queries) DeleteOldManifests(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteOldManifests)
	return err
}

const getActiveAdsWithPrioritiesWithCreatives = `-- name: GetActiveAdsWithPrioritiesWithCreatives :many
SELECT
    awp.id,
    awp.underlying_order_id,
    awp.order_id,
    awp.board_type_id,
    awp.ad_minutes,
    awp.time_of_week_range,
    awp.completion_seconds,
    awp.priority,
    o.status as order_status,
    o.total_dollars,
    uo.priority as underlying_order_priority,
    uo.destination_url,
    uo.utm_tag,
    cg.id as creative_group_id,
    cg.name as creative_group_name,
    c.id as creative_id,
    c.asset_link,
    c.type as creative_type,
    bt.name as board_type_name,
    bt.width as board_type_width,
    bt.height as board_type_height
FROM ad_with_priority awp
INNER JOIN orders o ON awp.order_id = o.id
INNER JOIN underlying_orders uo ON awp.underlying_order_id = uo.id
LEFT JOIN creative_groups cg ON uo.link_to_creative_group = cg.id
LEFT JOIN creatives c ON c.creative_group_id = cg.id
LEFT JOIN board_types bt ON awp.board_type_id = bt.id
WHERE o.status = 'active'
ORDER BY awp.priority DESC, awp.created_at ASC
`

type GetActiveAdsWithPrioritiesWithCreativesRow struct {
	ID                      pgtype.UUID
	UnderlyingOrderID       int32
	OrderID                 pgtype.UUID
	BoardTypeID             int32
	AdMinutes               int32
	TimeOfWeekRange         []byte
	CompletionSeconds       pgtype.Int4
	Priority                pgtype.Int4
	OrderStatus             pgtype.Text
	TotalDollars            pgtype.Numeric
	UnderlyingOrderPriority int32
	DestinationUrl          pgtype.Text
	UtmTag                  pgtype.Text
	CreativeGroupID         pgtype.Int4
	CreativeGroupName       pgtype.Text
	CreativeID              pgtype.Int4
	AssetLink               pgtype.Text
	CreativeType            pgtype.Text
	BoardTypeName           pgtype.Text
	BoardTypeWidth          pgtype.Int4
	BoardTypeHeight         pgtype.Int4
}

func (q *Queries) GetActiveAdsWithPrioritiesWithCreatives(ctx context.Context) ([]GetActiveAdsWithPrioritiesWithCreativesRow, error) {
	rows, err := q.db.Query(ctx, getActiveAdsWithPrioritiesWithCreatives)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveAdsWithPrioritiesWithCreativesRow
	for rows.Next() {
		var i GetActiveAdsWithPrioritiesWithCreativesRow
		if err := rows.Scan(
			&i.ID,
			&i.UnderlyingOrderID,
			&i.OrderID,
			&i.BoardTypeID,
			&i.AdMinutes,
			&i.TimeOfWeekRange,
			&i.CompletionSeconds,
			&i.Priority,
			&i.OrderStatus,
			&i.TotalDollars,
			&i.UnderlyingOrderPriority,
			&i.DestinationUrl,
			&i.UtmTag,
			&i.CreativeGroupID,
			&i.CreativeGroupName,
			&i.CreativeID,
			&i.AssetLink,
			&i.CreativeType,
			&i.BoardTypeName,
			&i.BoardTypeWidth,
			&i.BoardTypeHeight,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActivePaidAds = `-- name: GetActivePaidAds :many
SELECT
    awp.id,
    awp.underlying_order_id,
    awp.order_id,
    awp.board_type_id,
    awp.ad_minutes,
    awp.time_of_week_range,
    awp.completion_seconds,
    o.status as order_status,
    o.total_dollars,
    uo.destination_url,
    uo.utm_tag
FROM ad_with_priority awp
INNER JOIN orders o ON awp.order_id = o.id
INNER JOIN underlying_orders uo ON awp.underlying_order_id = uo.id
WHERE o.status = 'active'
AND o.total_dollars > 0
`

type GetActivePaidAdsRow struct {
	ID                pgtype.UUID
	UnderlyingOrderID int32
	OrderID           pgtype.UUID
	BoardTypeID       int32
	AdMinutes         int32
	TimeOfWeekRange   []byte
	CompletionSeconds pgtype.Int4
	OrderStatus       pgtype.Text
	TotalDollars      pgtype.Numeric
	DestinationUrl    pgtype.Text
	UtmTag            pgtype.Text
}

func (q *Queries) GetActivePaidAds(ctx context.Context) ([]GetActivePaidAdsRow, error) {
	rows, err := q.db.Query(ctx, getActivePaidAds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActivePaidAdsRow
	for rows.Next() {
		var i GetActivePaidAdsRow
		if err := rows.Scan(
			&i.ID,
			&i.UnderlyingOrderID,
			&i.OrderID,
			&i.BoardTypeID,
			&i.AdMinutes,
			&i.TimeOfWeekRange,
			&i.CompletionSeconds,
			&i.OrderStatus,
			&i.TotalDollars,
			&i.DestinationUrl,
			&i.UtmTag,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveVendorAllocations = `-- name: GetActiveVendorAllocations :many
SELECT
    va.id, va.user_id, va.underlying_order_id, va.priority, va.recurring, va.board_ids, va.require_admin_approval, va.created_at, va.updated_at, va.time_to_show_mode, va.times_of_week, va.percentage, va.specific_dates,
    u.name as vendor_name
FROM vendor_allocations va
INNER JOIN users u ON va.user_id = u.id
WHERE va.priority > 0
`

type GetActiveVendorAllocationsRow struct {
	ID                   pgtype.UUID
	UserID               pgtype.UUID
	UnderlyingOrderID    int32
	Priority             int32
	Recurring            pgtype.Bool
	BoardIds             []string
	RequireAdminApproval pgtype.Bool
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	TimeToShowMode       string
	TimesOfWeek          []byte
	Percentage           pgtype.Int4
	SpecificDates        []pgtype.Date
	VendorName           pgtype.Text
}

func (q *Queries) GetActiveVendorAllocations(ctx context.Context) ([]GetActiveVendorAllocationsRow, error) {
	rows, err := q.db.Query(ctx, getActiveVendorAllocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveVendorAllocationsRow
	for rows.Next() {
		var i GetActiveVendorAllocationsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UnderlyingOrderID,
			&i.Priority,
			&i.Recurring,
			&i.BoardIds,
			&i.RequireAdminApproval,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TimeToShowMode,
			&i.TimesOfWeek,
			&i.Percentage,
			&i.SpecificDates,
			&i.VendorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveVendorAllocationsWithCreatives = `-- name: GetActiveVendorAllocationsWithCreatives :many
SELECT
    va.id,
    va.user_id,
    va.underlying_order_id,
    va.priority,
    va.recurring,
    va.board_ids,
    va.require_admin_approval,
    va.created_at,
    va.updated_at,
    va.time_to_show_mode,
    va.times_of_week,
    va.percentage,
    va.specific_dates,
    u.name as vendor_name,
    cg.id as creative_group_id,
    cg.name as creative_group_name,
    c.id as creative_id,
    c.asset_link,
    c.type as creative_type
FROM vendor_allocations va
INNER JOIN users u ON va.user_id = u.id
LEFT JOIN underlying_orders uo ON va.underlying_order_id = uo.id
LEFT JOIN creative_groups cg ON uo.link_to_creative_group = cg.id
LEFT JOIN creatives c ON c.creative_group_id = cg.id
WHERE va.priority > 0
ORDER BY va.priority DESC, va.created_at ASC
`

type GetActiveVendorAllocationsWithCreativesRow struct {
	ID                   pgtype.UUID
	UserID               pgtype.UUID
	UnderlyingOrderID    int32
	Priority             int32
	Recurring            pgtype.Bool
	BoardIds             []string
	RequireAdminApproval pgtype.Bool
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	TimeToShowMode       string
	TimesOfWeek          []byte
	Percentage           pgtype.Int4
	SpecificDates        []pgtype.Date
	VendorName           pgtype.Text
	CreativeGroupID      pgtype.Int4
	CreativeGroupName    pgtype.Text
	CreativeID           pgtype.Int4
	AssetLink            pgtype.Text
	CreativeType         pgtype.Text
}

func (q *Queries) GetActiveVendorAllocationsWithCreatives(ctx context.Context) ([]GetActiveVendorAllocationsWithCreativesRow, error) {
	rows, err := q.db.Query(ctx, getActiveVendorAllocationsWithCreatives)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveVendorAllocationsWithCreativesRow
	for rows.Next() {
		var i GetActiveVendorAllocationsWithCreativesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UnderlyingOrderID,
			&i.Priority,
			&i.Recurring,
			&i.BoardIds,
			&i.RequireAdminApproval,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TimeToShowMode,
			&i.TimesOfWeek,
			&i.Percentage,
			&i.SpecificDates,
			&i.VendorName,
			&i.CreativeGroupID,
			&i.CreativeGroupName,
			&i.CreativeID,
			&i.AssetLink,
			&i.CreativeType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBoardManifest = `-- name: GetBoardManifest :one
SELECT id, board_id, manifest_date, compiled_json, ad_minute_allocations, created_at, updated_at, is_published, creative_snapshot FROM daily_board_manifests
WHERE board_id = $1 AND manifest_date = $2
`

type GetBoardManifestParams struct {
	BoardID      pgtype.UUID
	ManifestDate pgtype.Date
}

func (q *Queries) GetBoardManifest(ctx context.Context, arg GetBoardManifestParams) (DailyBoardManifest, error) {
	row := q.db.QueryRow(ctx, getBoardManifest, arg.BoardID, arg.ManifestDate)
	var i DailyBoardManifest
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.ManifestDate,
		&i.CompiledJson,
		&i.AdMinuteAllocations,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsPublished,
		&i.CreativeSnapshot,
	)
	return i, err
}

const getBoardsWithActiveManifests = `-- name: GetBoardsWithActiveManifests :many
SELECT DISTINCT b.id, b.board_type_id, b.owner_id, b.device_id, b.approved, b.location, b.created_at, b.updated_at, b.last_sync_at, b.last_known_latitude, b.last_known_longitude, b.current_geo_zone, b.device_status, b.manifest_version, dbm.manifest_date, dbm.updated_at as manifest_updated_at
FROM boards b
INNER JOIN daily_board_manifests dbm ON b.id = dbm.board_id
WHERE dbm.is_published = true
AND dbm.manifest_date >= CURRENT_DATE - INTERVAL '7 days'
ORDER BY b.created_at
`

type GetBoardsWithActiveManifestsRow struct {
	ID                 pgtype.UUID
	BoardTypeID        pgtype.Int4
	OwnerID            pgtype.UUID
	DeviceID           pgtype.Text
	Approved           pgtype.Bool
	Location           pgtype.Text
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	LastSyncAt         pgtype.Timestamptz
	LastKnownLatitude  pgtype.Numeric
	LastKnownLongitude pgtype.Numeric
	CurrentGeoZone     pgtype.Text
	DeviceStatus       pgtype.Text
	ManifestVersion    pgtype.Int4
	ManifestDate       pgtype.Date
	ManifestUpdatedAt  pgtype.Timestamptz
}

func (q *Queries) GetBoardsWithActiveManifests(ctx context.Context) ([]GetBoardsWithActiveManifestsRow, error) {
	rows, err := q.db.Query(ctx, getBoardsWithActiveManifests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBoardsWithActiveManifestsRow
	for rows.Next() {
		var i GetBoardsWithActiveManifestsRow
		if err := rows.Scan(
			&i.ID,
			&i.BoardTypeID,
			&i.OwnerID,
			&i.DeviceID,
			&i.Approved,
			&i.Location,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastSyncAt,
			&i.LastKnownLatitude,
			&i.LastKnownLongitude,
			&i.CurrentGeoZone,
			&i.DeviceStatus,
			&i.ManifestVersion,
			&i.ManifestDate,
			&i.ManifestUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBoardsWithGeofences = `-- name: GetBoardsWithGeofences :many
SELECT
    b.id, b.board_type_id, b.owner_id, b.device_id, b.approved, b.location, b.created_at, b.updated_at, b.last_sync_at, b.last_known_latitude, b.last_known_longitude, b.current_geo_zone, b.device_status, b.manifest_version,
    bt.name as board_type_name,
    bt.width,
    bt.height
FROM boards b
LEFT JOIN board_types bt ON b.board_type_id = bt.id
WHERE b.approved = true
ORDER BY b.created_at
`

type GetBoardsWithGeofencesRow struct {
	ID                 pgtype.UUID
	BoardTypeID        pgtype.Int4
	OwnerID            pgtype.UUID
	DeviceID           pgtype.Text
	Approved           pgtype.Bool
	Location           pgtype.Text
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	LastSyncAt         pgtype.Timestamptz
	LastKnownLatitude  pgtype.Numeric
	LastKnownLongitude pgtype.Numeric
	CurrentGeoZone     pgtype.Text
	DeviceStatus       pgtype.Text
	ManifestVersion    pgtype.Int4
	BoardTypeName      pgtype.Text
	Width              pgtype.Int4
	Height             pgtype.Int4
}

func (q *Queries) GetBoardsWithGeofences(ctx context.Context) ([]GetBoardsWithGeofencesRow, error) {
	rows, err := q.db.Query(ctx, getBoardsWithGeofences)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBoardsWithGeofencesRow
	for rows.Next() {
		var i GetBoardsWithGeofencesRow
		if err := rows.Scan(
			&i.ID,
			&i.BoardTypeID,
			&i.OwnerID,
			&i.DeviceID,
			&i.Approved,
			&i.Location,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastSyncAt,
			&i.LastKnownLatitude,
			&i.LastKnownLongitude,
			&i.CurrentGeoZone,
			&i.DeviceStatus,
			&i.ManifestVersion,
			&i.BoardTypeName,
			&i.Width,
			&i.Height,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGeoJSONByUnderlyingOrder = `-- name: GetGeoJSONByUnderlyingOrder :many
SELECT
    gf.id,
    gf.name,
    gf.postal_code,
    ST_AsGeoJSON(gf.geometry)::text as geojson
FROM underlying_order_geo_features uogf
INNER JOIN geo_features gf ON uogf.geo_feature_id = gf.id
WHERE uogf.underlying_order_id = $1
`

type GetGeoJSONByUnderlyingOrderRow struct {
	ID         pgtype.UUID
	Name       pgtype.Text
	PostalCode pgtype.Text
	Geojson    string
}

func (q *Queries) GetGeoJSONByUnderlyingOrder(ctx context.Context, underlyingOrderID int32) ([]GetGeoJSONByUnderlyingOrderRow, error) {
	rows, err := q.db.Query(ctx, getGeoJSONByUnderlyingOrder, underlyingOrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGeoJSONByUnderlyingOrderRow
	for rows.Next() {
		var i GetGeoJSONByUnderlyingOrderRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PostalCode,
			&i.Geojson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestBoardManifest = `-- name: GetLatestBoardManifest :one
SELECT id, board_id, manifest_date, compiled_json, ad_minute_allocations, created_at, updated_at, is_published, creative_snapshot FROM daily_board_manifests
WHERE board_id = $1 AND is_published = true
ORDER BY manifest_date DESC, updated_at DESC
LIMIT 1
`

func (q *Queries) GetLatestBoardManifest(ctx context.Context, boardID pgtype.UUID) (DailyBoardManifest, error) {
	row := q.db.QueryRow(ctx, getLatestBoardManifest, boardID)
	var i DailyBoardManifest
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.ManifestDate,
		&i.CompiledJson,
		&i.AdMinuteAllocations,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsPublished,
		&i.CreativeSnapshot,
	)
	return i, err
}

const getManifestsByDateRange = `-- name: GetManifestsByDateRange :many
SELECT dbm.id, dbm.board_id, dbm.manifest_date, dbm.compiled_json, dbm.ad_minute_allocations, dbm.created_at, dbm.updated_at, dbm.is_published, dbm.creative_snapshot, b.location
FROM daily_board_manifests dbm
INNER JOIN boards b ON dbm.board_id = b.id
WHERE dbm.manifest_date BETWEEN $1 AND $2
AND ($3::uuid IS NULL OR dbm.board_id = $3)
ORDER BY dbm.manifest_date DESC, b.created_at
`

type GetManifestsByDateRangeParams struct {
	ManifestDate   pgtype.Date
	ManifestDate_2 pgtype.Date
	Column3        pgtype.UUID
}

type GetManifestsByDateRangeRow struct {
	ID                  pgtype.UUID
	BoardID             pgtype.UUID
	ManifestDate        pgtype.Date
	CompiledJson        []byte
	AdMinuteAllocations []byte
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	IsPublished         pgtype.Bool
	CreativeSnapshot    []byte
	Location            pgtype.Text
}

func (q *Queries) GetManifestsByDateRange(ctx context.Context, arg GetManifestsByDateRangeParams) ([]GetManifestsByDateRangeRow, error) {
	rows, err := q.db.Query(ctx, getManifestsByDateRange, arg.ManifestDate, arg.ManifestDate_2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetManifestsByDateRangeRow
	for rows.Next() {
		var i GetManifestsByDateRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.ManifestDate,
			&i.CompiledJson,
			&i.AdMinuteAllocations,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsPublished,
			&i.CreativeSnapshot,
			&i.Location,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markManifestPublished = `-- name: MarkManifestPublished :exec
UPDATE daily_board_manifests
SET
    is_published = true,
    updated_at = NOW()
WHERE board_id = $1 AND manifest_date = $2
`

type MarkManifestPublishedParams struct {
	BoardID      pgtype.UUID
	ManifestDate pgtype.Date
}

func (q *Queries) MarkManifestPublished(ctx context.Context, arg MarkManifestPublishedParams) error {
	_, err := q.db.Exec(ctx, markManifestPublished, arg.BoardID, arg.ManifestDate)
	return err
}

const unpublishManifest = `-- name: UnpublishManifest :exec
UPDATE daily_board_manifests
SET
    is_published = false,
    updated_at = NOW()
WHERE board_id = $1 AND manifest_date = $2
`

type UnpublishManifestParams struct {
	BoardID      pgtype.UUID
	ManifestDate pgtype.Date
}

func (q *Queries) UnpublishManifest(ctx context.Context, arg UnpublishManifestParams) error {
	_, err := q.db.Exec(ctx, unpublishManifest, arg.BoardID, arg.ManifestDate)
	return err
}

const updateBoardManifest = `-- name: UpdateBoardManifest :one
UPDATE daily_board_manifests
SET
    compiled_json = $3,
    ad_minute_allocations = $4,
    is_published = $5,
    creative_snapshot = $6,
    updated_at = NOW()
WHERE board_id = $1 AND manifest_date = $2
RETURNING id, board_id, manifest_date, compiled_json, ad_minute_allocations, created_at, updated_at, is_published, creative_snapshot
`

type UpdateBoardManifestParams struct {
	BoardID             pgtype.UUID
	ManifestDate        pgtype.Date
	CompiledJson        []byte
	AdMinuteAllocations []byte
	IsPublished         pgtype.Bool
	CreativeSnapshot    []byte
}

func (q *Queries) UpdateBoardManifest(ctx context.Context, arg UpdateBoardManifestParams) (DailyBoardManifest, error) {
	row := q.db.QueryRow(ctx, updateBoardManifest,
		arg.BoardID,
		arg.ManifestDate,
		arg.CompiledJson,
		arg.AdMinuteAllocations,
		arg.IsPublished,
		arg.CreativeSnapshot,
	)
	var i DailyBoardManifest
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.ManifestDate,
		&i.CompiledJson,
		&i.AdMinuteAllocations,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsPublished,
		&i.CreativeSnapshot,
	)
	return i, err
}

const upsertDailyBoardManifest = `-- name: UpsertDailyBoardManifest :one
INSERT INTO daily_board_manifests (
    board_id,
    manifest_date,
    compiled_json,
    ad_minute_allocations,
    is_published,
    creative_snapshot
) VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (board_id, manifest_date) DO UPDATE SET
    compiled_json = EXCLUDED.compiled_json,
    ad_minute_allocations = EXCLUDED.ad_minute_allocations,
    is_published = EXCLUDED.is_published,
    creative_snapshot = CASE 
        WHEN daily_board_manifests.creative_snapshot = '{}'::jsonb 
        THEN EXCLUDED.creative_snapshot
        ELSE daily_board_manifests.creative_snapshot
    END,
    updated_at = NOW()
RETURNING id, board_id, manifest_date, compiled_json, ad_minute_allocations, created_at, updated_at, is_published, creative_snapshot
`

type UpsertDailyBoardManifestParams struct {
	BoardID             pgtype.UUID
	ManifestDate        pgtype.Date
	CompiledJson        []byte
	AdMinuteAllocations []byte
	IsPublished         pgtype.Bool
	CreativeSnapshot    []byte
}

func (q *Queries) UpsertDailyBoardManifest(ctx context.Context, arg UpsertDailyBoardManifestParams) (DailyBoardManifest, error) {
	row := q.db.QueryRow(ctx, upsertDailyBoardManifest,
		arg.BoardID,
		arg.ManifestDate,
		arg.CompiledJson,
		arg.AdMinuteAllocations,
		arg.IsPublished,
		arg.CreativeSnapshot,
	)
	var i DailyBoardManifest
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.ManifestDate,
		&i.CompiledJson,
		&i.AdMinuteAllocations,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsPublished,
		&i.CreativeSnapshot,
	)
	return i, err
}
