// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type CreativeStatus string

const (
	CreativeStatusPending  CreativeStatus = "pending"
	CreativeStatusApproved CreativeStatus = "approved"
	CreativeStatusRejected CreativeStatus = "rejected"
)

func (e *CreativeStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CreativeStatus(s)
	case string:
		*e = CreativeStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CreativeStatus: %T", src)
	}
	return nil
}

type NullCreativeStatus struct {
	CreativeStatus CreativeStatus
	Valid          bool // Valid is true if CreativeStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCreativeStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CreativeStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CreativeStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCreativeStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CreativeStatus), nil
}

type MediaType string

const (
	MediaTypeImage MediaType = "image"
	MediaTypeVideo MediaType = "video"
)

func (e *MediaType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MediaType(s)
	case string:
		*e = MediaType(s)
	default:
		return fmt.Errorf("unsupported scan type for MediaType: %T", src)
	}
	return nil
}

type NullMediaType struct {
	MediaType MediaType
	Valid     bool // Valid is true if MediaType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMediaType) Scan(value interface{}) error {
	if value == nil {
		ns.MediaType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MediaType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMediaType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MediaType), nil
}

type UserRole string

const (
	UserRoleUser       UserRole = "user"
	UserRoleHost       UserRole = "host"
	UserRoleSuperadmin UserRole = "superadmin"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Account struct {
	ID                pgtype.UUID
	UserID            pgtype.UUID
	Type              string
	Provider          string
	ProviderAccountID string
	RefreshToken      pgtype.Text
	AccessToken       pgtype.Text
	ExpiresAt         pgtype.Int8
	TokenType         pgtype.Text
	Scope             pgtype.Text
	IDToken           pgtype.Text
	SessionState      pgtype.Text
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type AdGeoFeature struct {
	AdID         pgtype.UUID
	GeoFeatureID pgtype.UUID
}

// Geographic minute allocations for ads. Geographic zones come from underlying_order_geo_features, not from a separate targeting field.
type AdGeoMinuteAllocation struct {
	ID                  pgtype.UUID
	AdWithPriorityID    pgtype.UUID
	GeoFeatureID        pgtype.UUID
	TargetMinutesPerDay int32
	AllocatedMinutes    int32
	PlayedMinutes       int32
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type AdPriorityConfig struct {
	Value        int32
	Name         string
	Description  string
	Location     pgtype.Text
	Multiplier   string
	PricePerHour int32
	PriceLabel   string
	Type         string
	SortOrder    int32
}

type AdWithPriority struct {
	ID                pgtype.UUID
	UnderlyingOrderID int32
	OrderID           pgtype.UUID
	BoardTypeID       int32
	AdMinutes         int32
	TimeOfWeekRange   []byte
	CompletionSeconds pgtype.Int4
	Priority          pgtype.Int4
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type Board struct {
	ID                 pgtype.UUID
	BoardTypeID        pgtype.Int4
	OwnerID            pgtype.UUID
	DeviceID           pgtype.Text
	Approved           pgtype.Bool
	Location           pgtype.Text
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	LastSyncAt         pgtype.Timestamptz
	LastKnownLatitude  pgtype.Numeric
	LastKnownLongitude pgtype.Numeric
	CurrentGeoZone     pgtype.Text
	DeviceStatus       pgtype.Text
	ManifestVersion    pgtype.Int4
}

type BoardMedium struct {
	ID        pgtype.UUID
	BoardID   pgtype.UUID
	Url       string
	Type      MediaType
	Caption   pgtype.Text
	IsPrimary pgtype.Bool
	SortOrder pgtype.Int4
	CreatedAt pgtype.Timestamptz
}

type BoardType struct {
	ID          int32
	Name        string
	Description pgtype.Text
	Dimensions  pgtype.Text
	Width       int32
	Height      int32
	HourlyPrice int32
}

type Creative struct {
	ID              int32
	CreativeGroupID pgtype.Int4
	AssetLink       string
	Type            string
	DateAdded       pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	Status          CreativeStatus
}

type CreativeGroup struct {
	ID        int32
	Name      string
	Approved  pgtype.Bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type DailyBoardManifest struct {
	ID                  pgtype.UUID
	BoardID             pgtype.UUID
	ManifestDate        pgtype.Date
	CompiledJson        []byte
	AdMinuteAllocations []byte
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	IsPublished         pgtype.Bool
	// Stores the list of creative IDs that were included when this manifest was first compiled.
	// Used to prevent new creatives from being added to existing day manifests during hourly recompilation.
	// Structure: {"creative_ids": [1, 2, 3], "compiled_at": "2024-01-15T14:00:00Z", "version": 1}
	CreativeSnapshot []byte
}

type GeoFeature struct {
	ID         pgtype.UUID
	Name       pgtype.Text
	PostalCode pgtype.Text
	SourceType string
	Geometry   interface{}
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type ManifestGeofence struct {
	ID           pgtype.UUID
	ManifestID   pgtype.UUID
	GeoFeatureID pgtype.UUID
	ZoneName     string
	CreatedAt    pgtype.Timestamptz
}

type MinutesAvailable struct {
	ID               pgtype.UUID
	BoardID          pgtype.UUID
	MinutesAvailable int32
	TimeOfDayRange   string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	DeprecatedAt     pgtype.Timestamptz
}

type MinutesAvailableGeoFeature struct {
	MinutesAvailableID pgtype.UUID
	GeoFeatureID       pgtype.UUID
	DeprecatedAt       pgtype.Timestamptz
}

type Order struct {
	ID                   pgtype.UUID
	UserID               pgtype.UUID
	RequireAdminApproval pgtype.Bool
	Status               pgtype.Text
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	CreditSpent          pgtype.Numeric
	TotalDollars         pgtype.Numeric
}

type PlayLog struct {
	ID              pgtype.UUID
	ContentType     string
	ContentID       string
	PlayedAt        pgtype.Timestamptz
	DurationSeconds int32
}

type Referral struct {
	ID             pgtype.UUID
	ReferrerID     pgtype.UUID
	RefereeID      pgtype.UUID
	CreditsAwarded pgtype.Numeric
	Status         pgtype.Text
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type Refund struct {
	ID          pgtype.UUID
	OrderID     pgtype.UUID
	Amount      pgtype.Numeric
	Reason      pgtype.Text
	AdminUserID pgtype.UUID
	Status      pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Session struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	SessionToken string
	Expires      pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type UnderlyingOrder struct {
	ID                  int32
	Priority            int32
	LinkToCreativeGroup pgtype.Int4
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	DestinationUrl      pgtype.Text
	UtmTag              pgtype.Text
}

type UnderlyingOrderGeoFeature struct {
	UnderlyingOrderID int32
	GeoFeatureID      pgtype.UUID
}

type User struct {
	ID               pgtype.UUID
	Name             pgtype.Text
	Email            string
	EmailVerified    pgtype.Timestamptz
	Image            pgtype.Text
	NextAuthID       pgtype.Text
	StripeCustomerID pgtype.Text
	Credits          pgtype.Numeric
	Role             UserRole
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	PasswordHash     pgtype.Text
}

type VendorAllocation struct {
	ID                   pgtype.UUID
	UserID               pgtype.UUID
	UnderlyingOrderID    int32
	Priority             int32
	Recurring            pgtype.Bool
	BoardIds             []string
	RequireAdminApproval pgtype.Bool
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	TimeToShowMode       string
	TimesOfWeek          []byte
	Percentage           pgtype.Int4
	SpecificDates        []pgtype.Date
}

type VendorAllocationPriorityConfig struct {
	Value        int32
	Name         string
	Description  string
	AllowedRoles []string
	SortOrder    int32
}

type VerificationToken struct {
	Identifier string
	Token      string
	Expires    pgtype.Timestamptz
}
