// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: orders.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveCreativeGroup = `-- name: ApproveCreativeGroup :one
UPDATE creative_groups
SET approved = true,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, approved, created_at, updated_at
`

func (q *Queries) ApproveCreativeGroup(ctx context.Context, id int32) (CreativeGroup, error) {
	row := q.db.QueryRow(ctx, approveCreativeGroup, id)
	var i CreativeGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Approved,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAdWithPriority = `-- name: CreateAdWithPriority :one
INSERT INTO ad_with_priority (
		underlying_order_id,
		order_id,
		board_type_id,
		ad_minutes,
		time_of_week_range,
		priority
	)
VALUES ($1, $2, $3, $4, $5::jsonb, $6)
RETURNING id, underlying_order_id, order_id, board_type_id, ad_minutes, time_of_week_range, completion_seconds, priority, created_at, updated_at
`

type CreateAdWithPriorityParams struct {
	UnderlyingOrderID int32
	OrderID           pgtype.UUID
	BoardTypeID       int32
	AdMinutes         int32
	Column5           []byte
	Priority          pgtype.Int4
}

func (q *Queries) CreateAdWithPriority(ctx context.Context, arg CreateAdWithPriorityParams) (AdWithPriority, error) {
	row := q.db.QueryRow(ctx, createAdWithPriority,
		arg.UnderlyingOrderID,
		arg.OrderID,
		arg.BoardTypeID,
		arg.AdMinutes,
		arg.Column5,
		arg.Priority,
	)
	var i AdWithPriority
	err := row.Scan(
		&i.ID,
		&i.UnderlyingOrderID,
		&i.OrderID,
		&i.BoardTypeID,
		&i.AdMinutes,
		&i.TimeOfWeekRange,
		&i.CompletionSeconds,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCreative = `-- name: CreateCreative :one
INSERT INTO creatives (creative_group_id, asset_link, type, status)
VALUES ($1, $2, $3, 'pending')
RETURNING id, creative_group_id, asset_link, type, date_added, created_at, updated_at, status
`

type CreateCreativeParams struct {
	CreativeGroupID pgtype.Int4
	AssetLink       string
	Type            string
}

func (q *Queries) CreateCreative(ctx context.Context, arg CreateCreativeParams) (Creative, error) {
	row := q.db.QueryRow(ctx, createCreative, arg.CreativeGroupID, arg.AssetLink, arg.Type)
	var i Creative
	err := row.Scan(
		&i.ID,
		&i.CreativeGroupID,
		&i.AssetLink,
		&i.Type,
		&i.DateAdded,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
	)
	return i, err
}

const createCreativeGroup = `-- name: CreateCreativeGroup :one
INSERT INTO creative_groups (name, approved)
VALUES ($1, false)
RETURNING id, name, approved, created_at, updated_at
`

func (q *Queries) CreateCreativeGroup(ctx context.Context, name string) (CreativeGroup, error) {
	row := q.db.QueryRow(ctx, createCreativeGroup, name)
	var i CreativeGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Approved,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createGeoFeature = `-- name: CreateGeoFeature :one
INSERT INTO geo_features (name, postal_code, source_type, geometry)
VALUES ($1, $2, $3, ST_GeomFromGeoJSON($4)::geography)
RETURNING id,
	name,
	postal_code,
	source_type,
	ST_AsGeoJSON(geometry)::text AS geometry,
	created_at,
	updated_at
`

type CreateGeoFeatureParams struct {
	Name              pgtype.Text
	PostalCode        pgtype.Text
	SourceType        string
	StGeomfromgeojson interface{}
}

type CreateGeoFeatureRow struct {
	ID         pgtype.UUID
	Name       pgtype.Text
	PostalCode pgtype.Text
	SourceType string
	Geometry   string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

// Convert geometry to GeoJSON text for Go scanning compatibility (PostGIS geometry types cannot be scanned into interface{})
func (q *Queries) CreateGeoFeature(ctx context.Context, arg CreateGeoFeatureParams) (CreateGeoFeatureRow, error) {
	row := q.db.QueryRow(ctx, createGeoFeature,
		arg.Name,
		arg.PostalCode,
		arg.SourceType,
		arg.StGeomfromgeojson,
	)
	var i CreateGeoFeatureRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PostalCode,
		&i.SourceType,
		&i.Geometry,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
		user_id,
		require_admin_approval,
		status,
		credit_spent,
		total_dollars
	)
VALUES ($1, true, 'pending', $2, $2)
RETURNING id, user_id, require_admin_approval, status, created_at, updated_at, credit_spent, total_dollars
`

type CreateOrderParams struct {
	UserID      pgtype.UUID
	CreditSpent pgtype.Numeric
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder, arg.UserID, arg.CreditSpent)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RequireAdminApproval,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreditSpent,
		&i.TotalDollars,
	)
	return i, err
}

const createRefund = `-- name: CreateRefund :one
INSERT INTO refunds (order_id, amount, reason, status, admin_user_id)
VALUES ($1, $2, $3, 'processed', $4)
RETURNING id,
	order_id,
	amount,
	reason,
	status,
	admin_user_id,
	created_at,
	updated_at
`

type CreateRefundParams struct {
	OrderID     pgtype.UUID
	Amount      pgtype.Numeric
	Reason      pgtype.Text
	AdminUserID pgtype.UUID
}

type CreateRefundRow struct {
	ID          pgtype.UUID
	OrderID     pgtype.UUID
	Amount      pgtype.Numeric
	Reason      pgtype.Text
	Status      pgtype.Text
	AdminUserID pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) CreateRefund(ctx context.Context, arg CreateRefundParams) (CreateRefundRow, error) {
	row := q.db.QueryRow(ctx, createRefund,
		arg.OrderID,
		arg.Amount,
		arg.Reason,
		arg.AdminUserID,
	)
	var i CreateRefundRow
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Amount,
		&i.Reason,
		&i.Status,
		&i.AdminUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUnderlyingOrder = `-- name: CreateUnderlyingOrder :one
INSERT INTO underlying_orders (
		priority,
		link_to_creative_group,
		destination_url,
		utm_tag
	)
VALUES ($1, $2, $3, $4)
RETURNING id, priority, link_to_creative_group, created_at, updated_at, destination_url, utm_tag
`

type CreateUnderlyingOrderParams struct {
	Priority            int32
	LinkToCreativeGroup pgtype.Int4
	DestinationUrl      pgtype.Text
	UtmTag              pgtype.Text
}

// Note: service_area is no longer stored directly in underlying_orders
// Service areas are tracked through underlying_order_geo_features join table
func (q *Queries) CreateUnderlyingOrder(ctx context.Context, arg CreateUnderlyingOrderParams) (UnderlyingOrder, error) {
	row := q.db.QueryRow(ctx, createUnderlyingOrder,
		arg.Priority,
		arg.LinkToCreativeGroup,
		arg.DestinationUrl,
		arg.UtmTag,
	)
	var i UnderlyingOrder
	err := row.Scan(
		&i.ID,
		&i.Priority,
		&i.LinkToCreativeGroup,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DestinationUrl,
		&i.UtmTag,
	)
	return i, err
}

const deductUserCredits = `-- name: DeductUserCredits :one
UPDATE users
SET credits = credits - $1::numeric,
	updated_at = NOW()
WHERE id = $2
RETURNING credits
`

type DeductUserCreditsParams struct {
	Credits pgtype.Numeric
	ID      pgtype.UUID
}

func (q *Queries) DeductUserCredits(ctx context.Context, arg DeductUserCreditsParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, deductUserCredits, arg.Credits, arg.ID)
	var credits pgtype.Numeric
	err := row.Scan(&credits)
	return credits, err
}

const deleteCreativesByCreativeGroupID = `-- name: DeleteCreativesByCreativeGroupID :exec
DELETE FROM creatives
WHERE creative_group_id = $1
`

func (q *Queries) DeleteCreativesByCreativeGroupID(ctx context.Context, creativeGroupID pgtype.Int4) error {
	_, err := q.db.Exec(ctx, deleteCreativesByCreativeGroupID, creativeGroupID)
	return err
}

const deleteUnderlyingOrderGeoFeatures = `-- name: DeleteUnderlyingOrderGeoFeatures :exec
DELETE FROM underlying_order_geo_features
WHERE underlying_order_id = $1
`

func (q *Queries) DeleteUnderlyingOrderGeoFeatures(ctx context.Context, underlyingOrderID int32) error {
	_, err := q.db.Exec(ctx, deleteUnderlyingOrderGeoFeatures, underlyingOrderID)
	return err
}

const getCreativeByID = `-- name: GetCreativeByID :one
SELECT id,
	creative_group_id,
	asset_link,
	type,
	status,
	date_added,
	created_at,
	updated_at
FROM creatives
WHERE id = $1
`

type GetCreativeByIDRow struct {
	ID              int32
	CreativeGroupID pgtype.Int4
	AssetLink       string
	Type            string
	Status          CreativeStatus
	DateAdded       pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) GetCreativeByID(ctx context.Context, id int32) (GetCreativeByIDRow, error) {
	row := q.db.QueryRow(ctx, getCreativeByID, id)
	var i GetCreativeByIDRow
	err := row.Scan(
		&i.ID,
		&i.CreativeGroupID,
		&i.AssetLink,
		&i.Type,
		&i.Status,
		&i.DateAdded,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id,
	user_id,
	require_admin_approval,
	status,
	created_at,
	updated_at,
	credit_spent,
	total_dollars
FROM orders
WHERE id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id pgtype.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RequireAdminApproval,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreditSpent,
		&i.TotalDollars,
	)
	return i, err
}

const getOrderDetailsByID = `-- name: GetOrderDetailsByID :one
SELECT o.id AS order_id,
	o.user_id AS order_user_id,
	o.require_admin_approval AS order_require_admin_approval,
	o.status AS order_status,
	o.created_at AS order_created_at,
	o.updated_at AS order_updated_at,
	o.credit_spent AS order_credit_spent,
	o.total_dollars AS order_total_dollars,
	a.id AS ad_id,
	a.underlying_order_id AS ad_underlying_order_id,
	a.order_id AS ad_order_id,
	a.board_type_id AS ad_board_type_id,
	a.ad_minutes AS ad_ad_minutes,
	a.time_of_week_range AS ad_time_of_week_range,
	a.priority AS ad_priority,
	a.completion_seconds AS ad_completion_seconds,
	a.created_at AS ad_created_at,
	a.updated_at AS ad_updated_at,
	uo.id AS underlying_order_id,
	uo.priority AS underlying_order_priority,
	uo.link_to_creative_group AS underlying_order_link_to_creative_group,
	uo.destination_url AS underlying_order_destination_url,
	uo.utm_tag AS underlying_order_utm_tag,
	uo.created_at AS underlying_order_created_at,
	uo.updated_at AS underlying_order_updated_at,
	cg.id AS creative_group_id,
	cg.name AS creative_group_name,
	cg.approved AS creative_group_approved,
	cg.created_at AS creative_group_created_at,
	cg.updated_at AS creative_group_updated_at,
	bt.id AS board_type_id,
	bt.name AS board_type_name,
	bt.description AS board_type_description,
	bt.dimensions AS board_type_dimensions,
	bt.width AS board_type_width,
	bt.height AS board_type_height,
	bt.hourly_price AS board_type_hourly_price,
	u.id AS owner_id,
	u.name AS owner_name,
	u.email AS owner_email
FROM orders o
	JOIN ad_with_priority a ON a.order_id = o.id
	JOIN underlying_orders uo ON uo.id = a.underlying_order_id
	JOIN creative_groups cg ON cg.id = uo.link_to_creative_group
	LEFT JOIN board_types bt ON bt.id = a.board_type_id
	LEFT JOIN users u ON u.id = o.user_id
WHERE o.id = $1
`

type GetOrderDetailsByIDRow struct {
	OrderID                            pgtype.UUID
	OrderUserID                        pgtype.UUID
	OrderRequireAdminApproval          pgtype.Bool
	OrderStatus                        pgtype.Text
	OrderCreatedAt                     pgtype.Timestamptz
	OrderUpdatedAt                     pgtype.Timestamptz
	OrderCreditSpent                   pgtype.Numeric
	OrderTotalDollars                  pgtype.Numeric
	AdID                               pgtype.UUID
	AdUnderlyingOrderID                int32
	AdOrderID                          pgtype.UUID
	AdBoardTypeID                      int32
	AdAdMinutes                        int32
	AdTimeOfWeekRange                  []byte
	AdPriority                         pgtype.Int4
	AdCompletionSeconds                pgtype.Int4
	AdCreatedAt                        pgtype.Timestamptz
	AdUpdatedAt                        pgtype.Timestamptz
	UnderlyingOrderID                  int32
	UnderlyingOrderPriority            int32
	UnderlyingOrderLinkToCreativeGroup pgtype.Int4
	UnderlyingOrderDestinationUrl      pgtype.Text
	UnderlyingOrderUtmTag              pgtype.Text
	UnderlyingOrderCreatedAt           pgtype.Timestamptz
	UnderlyingOrderUpdatedAt           pgtype.Timestamptz
	CreativeGroupID                    int32
	CreativeGroupName                  string
	CreativeGroupApproved              pgtype.Bool
	CreativeGroupCreatedAt             pgtype.Timestamptz
	CreativeGroupUpdatedAt             pgtype.Timestamptz
	BoardTypeID                        pgtype.Int4
	BoardTypeName                      pgtype.Text
	BoardTypeDescription               pgtype.Text
	BoardTypeDimensions                pgtype.Text
	BoardTypeWidth                     pgtype.Int4
	BoardTypeHeight                    pgtype.Int4
	BoardTypeHourlyPrice               pgtype.Int4
	OwnerID                            pgtype.UUID
	OwnerName                          pgtype.Text
	OwnerEmail                         pgtype.Text
}

func (q *Queries) GetOrderDetailsByID(ctx context.Context, id pgtype.UUID) (GetOrderDetailsByIDRow, error) {
	row := q.db.QueryRow(ctx, getOrderDetailsByID, id)
	var i GetOrderDetailsByIDRow
	err := row.Scan(
		&i.OrderID,
		&i.OrderUserID,
		&i.OrderRequireAdminApproval,
		&i.OrderStatus,
		&i.OrderCreatedAt,
		&i.OrderUpdatedAt,
		&i.OrderCreditSpent,
		&i.OrderTotalDollars,
		&i.AdID,
		&i.AdUnderlyingOrderID,
		&i.AdOrderID,
		&i.AdBoardTypeID,
		&i.AdAdMinutes,
		&i.AdTimeOfWeekRange,
		&i.AdPriority,
		&i.AdCompletionSeconds,
		&i.AdCreatedAt,
		&i.AdUpdatedAt,
		&i.UnderlyingOrderID,
		&i.UnderlyingOrderPriority,
		&i.UnderlyingOrderLinkToCreativeGroup,
		&i.UnderlyingOrderDestinationUrl,
		&i.UnderlyingOrderUtmTag,
		&i.UnderlyingOrderCreatedAt,
		&i.UnderlyingOrderUpdatedAt,
		&i.CreativeGroupID,
		&i.CreativeGroupName,
		&i.CreativeGroupApproved,
		&i.CreativeGroupCreatedAt,
		&i.CreativeGroupUpdatedAt,
		&i.BoardTypeID,
		&i.BoardTypeName,
		&i.BoardTypeDescription,
		&i.BoardTypeDimensions,
		&i.BoardTypeWidth,
		&i.BoardTypeHeight,
		&i.BoardTypeHourlyPrice,
		&i.OwnerID,
		&i.OwnerName,
		&i.OwnerEmail,
	)
	return i, err
}

const getOrderUserByCreativeGroupID = `-- name: GetOrderUserByCreativeGroupID :one
SELECT DISTINCT o.user_id,
	u.email,
	u.name,
	o.id AS order_id
FROM orders o
	JOIN ad_with_priority a ON a.order_id = o.id
	JOIN underlying_orders uo ON uo.id = a.underlying_order_id
	JOIN users u ON u.id = o.user_id
WHERE uo.link_to_creative_group = $1
LIMIT 1
`

type GetOrderUserByCreativeGroupIDRow struct {
	UserID  pgtype.UUID
	Email   string
	Name    pgtype.Text
	OrderID pgtype.UUID
}

func (q *Queries) GetOrderUserByCreativeGroupID(ctx context.Context, linkToCreativeGroup pgtype.Int4) (GetOrderUserByCreativeGroupIDRow, error) {
	row := q.db.QueryRow(ctx, getOrderUserByCreativeGroupID, linkToCreativeGroup)
	var i GetOrderUserByCreativeGroupIDRow
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.Name,
		&i.OrderID,
	)
	return i, err
}

const getUserCredits = `-- name: GetUserCredits :one
SELECT credits
FROM users
WHERE id = $1
`

func (q *Queries) GetUserCredits(ctx context.Context, id pgtype.UUID) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getUserCredits, id)
	var credits pgtype.Numeric
	err := row.Scan(&credits)
	return credits, err
}

const incrementAdCompletionSeconds = `-- name: IncrementAdCompletionSeconds :exec
UPDATE ad_with_priority
SET completion_seconds = COALESCE(completion_seconds, 0) + $2,
    updated_at = NOW()
WHERE id = $1::uuid
`

type IncrementAdCompletionSecondsParams struct {
	Column1           pgtype.UUID
	CompletionSeconds pgtype.Int4
}

func (q *Queries) IncrementAdCompletionSeconds(ctx context.Context, arg IncrementAdCompletionSecondsParams) error {
	_, err := q.db.Exec(ctx, incrementAdCompletionSeconds, arg.Column1, arg.CompletionSeconds)
	return err
}

const linkUnderlyingOrderGeoFeature = `-- name: LinkUnderlyingOrderGeoFeature :exec
INSERT INTO underlying_order_geo_features (underlying_order_id, geo_feature_id)
VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type LinkUnderlyingOrderGeoFeatureParams struct {
	UnderlyingOrderID int32
	GeoFeatureID      pgtype.UUID
}

func (q *Queries) LinkUnderlyingOrderGeoFeature(ctx context.Context, arg LinkUnderlyingOrderGeoFeatureParams) error {
	_, err := q.db.Exec(ctx, linkUnderlyingOrderGeoFeature, arg.UnderlyingOrderID, arg.GeoFeatureID)
	return err
}

const listCreativesByCreativeGroupIDs = `-- name: ListCreativesByCreativeGroupIDs :many
SELECT id,
	creative_group_id,
	asset_link,
	type,
	status,
	date_added,
	created_at,
	updated_at
FROM creatives
WHERE creative_group_id = ANY($1::int [])
`

type ListCreativesByCreativeGroupIDsRow struct {
	ID              int32
	CreativeGroupID pgtype.Int4
	AssetLink       string
	Type            string
	Status          CreativeStatus
	DateAdded       pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) ListCreativesByCreativeGroupIDs(ctx context.Context, creativeGroupIds []int32) ([]ListCreativesByCreativeGroupIDsRow, error) {
	rows, err := q.db.Query(ctx, listCreativesByCreativeGroupIDs, creativeGroupIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCreativesByCreativeGroupIDsRow
	for rows.Next() {
		var i ListCreativesByCreativeGroupIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreativeGroupID,
			&i.AssetLink,
			&i.Type,
			&i.Status,
			&i.DateAdded,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGeoFeaturesByUnderlyingOrderIDs = `-- name: ListGeoFeaturesByUnderlyingOrderIDs :many
SELECT uo.underlying_order_id,
	g.id AS geo_id,
	g.name AS geo_name,
	g.postal_code AS geo_postal_code,
	g.source_type AS geo_source_type,
	ST_AsGeoJSON(g.geometry)::text AS geo_geometry,
	g.created_at AS geo_created_at,
	g.updated_at AS geo_updated_at
FROM underlying_order_geo_features uo
	JOIN geo_features g ON g.id = uo.geo_feature_id
WHERE uo.underlying_order_id = ANY($1::int [])
`

type ListGeoFeaturesByUnderlyingOrderIDsRow struct {
	UnderlyingOrderID int32
	GeoID             pgtype.UUID
	GeoName           pgtype.Text
	GeoPostalCode     pgtype.Text
	GeoSourceType     string
	GeoGeometry       string
	GeoCreatedAt      pgtype.Timestamptz
	GeoUpdatedAt      pgtype.Timestamptz
}

func (q *Queries) ListGeoFeaturesByUnderlyingOrderIDs(ctx context.Context, underlyingOrderIds []int32) ([]ListGeoFeaturesByUnderlyingOrderIDsRow, error) {
	rows, err := q.db.Query(ctx, listGeoFeaturesByUnderlyingOrderIDs, underlyingOrderIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGeoFeaturesByUnderlyingOrderIDsRow
	for rows.Next() {
		var i ListGeoFeaturesByUnderlyingOrderIDsRow
		if err := rows.Scan(
			&i.UnderlyingOrderID,
			&i.GeoID,
			&i.GeoName,
			&i.GeoPostalCode,
			&i.GeoSourceType,
			&i.GeoGeometry,
			&i.GeoCreatedAt,
			&i.GeoUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByStatus = `-- name: ListOrdersByStatus :many
SELECT o.id AS order_id,
	o.user_id AS order_user_id,
	o.require_admin_approval AS order_require_admin_approval,
	o.status AS order_status,
	o.created_at AS order_created_at,
	o.updated_at AS order_updated_at,
	o.credit_spent AS order_credit_spent,
	o.total_dollars AS order_total_dollars,
	a.id AS ad_id,
	a.underlying_order_id AS ad_underlying_order_id,
	a.order_id AS ad_order_id,
	a.board_type_id AS ad_board_type_id,
	a.ad_minutes AS ad_ad_minutes,
	a.time_of_week_range AS ad_time_of_week_range,
	a.priority AS ad_priority,
	a.completion_seconds AS ad_completion_seconds,
	a.created_at AS ad_created_at,
	a.updated_at AS ad_updated_at,
	uo.id AS underlying_order_id,
	uo.priority AS underlying_order_priority,
	uo.link_to_creative_group AS underlying_order_link_to_creative_group,
	uo.destination_url AS underlying_order_destination_url,
	uo.utm_tag AS underlying_order_utm_tag,
	uo.created_at AS underlying_order_created_at,
	uo.updated_at AS underlying_order_updated_at,
	cg.id AS creative_group_id,
	cg.name AS creative_group_name,
	cg.approved AS creative_group_approved,
	cg.created_at AS creative_group_created_at,
	cg.updated_at AS creative_group_updated_at,
	bt.id AS board_type_id,
	bt.name AS board_type_name,
	bt.description AS board_type_description,
	bt.dimensions AS board_type_dimensions,
	bt.width AS board_type_width,
	bt.height AS board_type_height,
	bt.hourly_price AS board_type_hourly_price,
	u.id AS owner_id,
	u.name AS owner_name,
	u.email AS owner_email
FROM orders o
	JOIN ad_with_priority a ON a.order_id = o.id
	JOIN underlying_orders uo ON uo.id = a.underlying_order_id
	JOIN creative_groups cg ON cg.id = uo.link_to_creative_group
	LEFT JOIN board_types bt ON bt.id = a.board_type_id
	LEFT JOIN users u ON u.id = o.user_id
WHERE o.status = ANY($2::text [])
ORDER BY o.created_at DESC
LIMIT $1
`

type ListOrdersByStatusParams struct {
	Limit    int32
	Statuses []string
}

type ListOrdersByStatusRow struct {
	OrderID                            pgtype.UUID
	OrderUserID                        pgtype.UUID
	OrderRequireAdminApproval          pgtype.Bool
	OrderStatus                        pgtype.Text
	OrderCreatedAt                     pgtype.Timestamptz
	OrderUpdatedAt                     pgtype.Timestamptz
	OrderCreditSpent                   pgtype.Numeric
	OrderTotalDollars                  pgtype.Numeric
	AdID                               pgtype.UUID
	AdUnderlyingOrderID                int32
	AdOrderID                          pgtype.UUID
	AdBoardTypeID                      int32
	AdAdMinutes                        int32
	AdTimeOfWeekRange                  []byte
	AdPriority                         pgtype.Int4
	AdCompletionSeconds                pgtype.Int4
	AdCreatedAt                        pgtype.Timestamptz
	AdUpdatedAt                        pgtype.Timestamptz
	UnderlyingOrderID                  int32
	UnderlyingOrderPriority            int32
	UnderlyingOrderLinkToCreativeGroup pgtype.Int4
	UnderlyingOrderDestinationUrl      pgtype.Text
	UnderlyingOrderUtmTag              pgtype.Text
	UnderlyingOrderCreatedAt           pgtype.Timestamptz
	UnderlyingOrderUpdatedAt           pgtype.Timestamptz
	CreativeGroupID                    int32
	CreativeGroupName                  string
	CreativeGroupApproved              pgtype.Bool
	CreativeGroupCreatedAt             pgtype.Timestamptz
	CreativeGroupUpdatedAt             pgtype.Timestamptz
	BoardTypeID                        pgtype.Int4
	BoardTypeName                      pgtype.Text
	BoardTypeDescription               pgtype.Text
	BoardTypeDimensions                pgtype.Text
	BoardTypeWidth                     pgtype.Int4
	BoardTypeHeight                    pgtype.Int4
	BoardTypeHourlyPrice               pgtype.Int4
	OwnerID                            pgtype.UUID
	OwnerName                          pgtype.Text
	OwnerEmail                         pgtype.Text
}

func (q *Queries) ListOrdersByStatus(ctx context.Context, arg ListOrdersByStatusParams) ([]ListOrdersByStatusRow, error) {
	rows, err := q.db.Query(ctx, listOrdersByStatus, arg.Limit, arg.Statuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrdersByStatusRow
	for rows.Next() {
		var i ListOrdersByStatusRow
		if err := rows.Scan(
			&i.OrderID,
			&i.OrderUserID,
			&i.OrderRequireAdminApproval,
			&i.OrderStatus,
			&i.OrderCreatedAt,
			&i.OrderUpdatedAt,
			&i.OrderCreditSpent,
			&i.OrderTotalDollars,
			&i.AdID,
			&i.AdUnderlyingOrderID,
			&i.AdOrderID,
			&i.AdBoardTypeID,
			&i.AdAdMinutes,
			&i.AdTimeOfWeekRange,
			&i.AdPriority,
			&i.AdCompletionSeconds,
			&i.AdCreatedAt,
			&i.AdUpdatedAt,
			&i.UnderlyingOrderID,
			&i.UnderlyingOrderPriority,
			&i.UnderlyingOrderLinkToCreativeGroup,
			&i.UnderlyingOrderDestinationUrl,
			&i.UnderlyingOrderUtmTag,
			&i.UnderlyingOrderCreatedAt,
			&i.UnderlyingOrderUpdatedAt,
			&i.CreativeGroupID,
			&i.CreativeGroupName,
			&i.CreativeGroupApproved,
			&i.CreativeGroupCreatedAt,
			&i.CreativeGroupUpdatedAt,
			&i.BoardTypeID,
			&i.BoardTypeName,
			&i.BoardTypeDescription,
			&i.BoardTypeDimensions,
			&i.BoardTypeWidth,
			&i.BoardTypeHeight,
			&i.BoardTypeHourlyPrice,
			&i.OwnerID,
			&i.OwnerName,
			&i.OwnerEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByUserID = `-- name: ListOrdersByUserID :many
SELECT id,
	user_id,
	require_admin_approval,
	status,
	created_at,
	updated_at,
	credit_spent,
	total_dollars
FROM orders
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListOrdersByUserIDParams struct {
	UserID pgtype.UUID
	Limit  int32
}

func (q *Queries) ListOrdersByUserID(ctx context.Context, arg ListOrdersByUserIDParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByUserID, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RequireAdminApproval,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreditSpent,
			&i.TotalDollars,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersCurrent = `-- name: ListOrdersCurrent :many
SELECT o.id AS order_id,
	o.user_id AS order_user_id,
	o.require_admin_approval AS order_require_admin_approval,
	o.status AS order_status,
	o.created_at AS order_created_at,
	o.updated_at AS order_updated_at,
	o.credit_spent AS order_credit_spent,
	o.total_dollars AS order_total_dollars,
	a.id AS ad_id,
	a.underlying_order_id AS ad_underlying_order_id,
	a.order_id AS ad_order_id,
	a.board_type_id AS ad_board_type_id,
	a.ad_minutes AS ad_ad_minutes,
	a.time_of_week_range AS ad_time_of_week_range,
	a.priority AS ad_priority,
	a.completion_seconds AS ad_completion_seconds,
	a.created_at AS ad_created_at,
	a.updated_at AS ad_updated_at,
	uo.id AS underlying_order_id,
	uo.priority AS underlying_order_priority,
	uo.link_to_creative_group AS underlying_order_link_to_creative_group,
	uo.destination_url AS underlying_order_destination_url,
	uo.utm_tag AS underlying_order_utm_tag,
	uo.created_at AS underlying_order_created_at,
	uo.updated_at AS underlying_order_updated_at,
	cg.id AS creative_group_id,
	cg.name AS creative_group_name,
	cg.approved AS creative_group_approved,
	cg.created_at AS creative_group_created_at,
	cg.updated_at AS creative_group_updated_at,
	bt.id AS board_type_id,
	bt.name AS board_type_name,
	bt.description AS board_type_description,
	bt.dimensions AS board_type_dimensions,
	bt.width AS board_type_width,
	bt.height AS board_type_height,
	bt.hourly_price AS board_type_hourly_price,
	u.id AS owner_id,
	u.name AS owner_name,
	u.email AS owner_email
FROM orders o
	JOIN ad_with_priority a ON a.order_id = o.id
	JOIN underlying_orders uo ON uo.id = a.underlying_order_id
	JOIN creative_groups cg ON cg.id = uo.link_to_creative_group
	LEFT JOIN board_types bt ON bt.id = a.board_type_id
	LEFT JOIN users u ON u.id = o.user_id
WHERE o.status IN ('pending', 'active')
ORDER BY o.created_at DESC
LIMIT $1
`

type ListOrdersCurrentRow struct {
	OrderID                            pgtype.UUID
	OrderUserID                        pgtype.UUID
	OrderRequireAdminApproval          pgtype.Bool
	OrderStatus                        pgtype.Text
	OrderCreatedAt                     pgtype.Timestamptz
	OrderUpdatedAt                     pgtype.Timestamptz
	OrderCreditSpent                   pgtype.Numeric
	OrderTotalDollars                  pgtype.Numeric
	AdID                               pgtype.UUID
	AdUnderlyingOrderID                int32
	AdOrderID                          pgtype.UUID
	AdBoardTypeID                      int32
	AdAdMinutes                        int32
	AdTimeOfWeekRange                  []byte
	AdPriority                         pgtype.Int4
	AdCompletionSeconds                pgtype.Int4
	AdCreatedAt                        pgtype.Timestamptz
	AdUpdatedAt                        pgtype.Timestamptz
	UnderlyingOrderID                  int32
	UnderlyingOrderPriority            int32
	UnderlyingOrderLinkToCreativeGroup pgtype.Int4
	UnderlyingOrderDestinationUrl      pgtype.Text
	UnderlyingOrderUtmTag              pgtype.Text
	UnderlyingOrderCreatedAt           pgtype.Timestamptz
	UnderlyingOrderUpdatedAt           pgtype.Timestamptz
	CreativeGroupID                    int32
	CreativeGroupName                  string
	CreativeGroupApproved              pgtype.Bool
	CreativeGroupCreatedAt             pgtype.Timestamptz
	CreativeGroupUpdatedAt             pgtype.Timestamptz
	BoardTypeID                        pgtype.Int4
	BoardTypeName                      pgtype.Text
	BoardTypeDescription               pgtype.Text
	BoardTypeDimensions                pgtype.Text
	BoardTypeWidth                     pgtype.Int4
	BoardTypeHeight                    pgtype.Int4
	BoardTypeHourlyPrice               pgtype.Int4
	OwnerID                            pgtype.UUID
	OwnerName                          pgtype.Text
	OwnerEmail                         pgtype.Text
}

func (q *Queries) ListOrdersCurrent(ctx context.Context, limit int32) ([]ListOrdersCurrentRow, error) {
	rows, err := q.db.Query(ctx, listOrdersCurrent, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrdersCurrentRow
	for rows.Next() {
		var i ListOrdersCurrentRow
		if err := rows.Scan(
			&i.OrderID,
			&i.OrderUserID,
			&i.OrderRequireAdminApproval,
			&i.OrderStatus,
			&i.OrderCreatedAt,
			&i.OrderUpdatedAt,
			&i.OrderCreditSpent,
			&i.OrderTotalDollars,
			&i.AdID,
			&i.AdUnderlyingOrderID,
			&i.AdOrderID,
			&i.AdBoardTypeID,
			&i.AdAdMinutes,
			&i.AdTimeOfWeekRange,
			&i.AdPriority,
			&i.AdCompletionSeconds,
			&i.AdCreatedAt,
			&i.AdUpdatedAt,
			&i.UnderlyingOrderID,
			&i.UnderlyingOrderPriority,
			&i.UnderlyingOrderLinkToCreativeGroup,
			&i.UnderlyingOrderDestinationUrl,
			&i.UnderlyingOrderUtmTag,
			&i.UnderlyingOrderCreatedAt,
			&i.UnderlyingOrderUpdatedAt,
			&i.CreativeGroupID,
			&i.CreativeGroupName,
			&i.CreativeGroupApproved,
			&i.CreativeGroupCreatedAt,
			&i.CreativeGroupUpdatedAt,
			&i.BoardTypeID,
			&i.BoardTypeName,
			&i.BoardTypeDescription,
			&i.BoardTypeDimensions,
			&i.BoardTypeWidth,
			&i.BoardTypeHeight,
			&i.BoardTypeHourlyPrice,
			&i.OwnerID,
			&i.OwnerName,
			&i.OwnerEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersToApprove = `-- name: ListOrdersToApprove :many
SELECT o.id AS order_id,
	o.user_id AS order_user_id,
	o.require_admin_approval AS order_require_admin_approval,
	o.status AS order_status,
	o.created_at AS order_created_at,
	o.updated_at AS order_updated_at,
	o.credit_spent AS order_credit_spent,
	o.total_dollars AS order_total_dollars,
	a.id AS ad_id,
	a.underlying_order_id AS ad_underlying_order_id,
	a.order_id AS ad_order_id,
	a.board_type_id AS ad_board_type_id,
	a.ad_minutes AS ad_ad_minutes,
	a.time_of_week_range AS ad_time_of_week_range,
	a.priority AS ad_priority,
	a.completion_seconds AS ad_completion_seconds,
	a.created_at AS ad_created_at,
	a.updated_at AS ad_updated_at,
	uo.id AS underlying_order_id,
	uo.priority AS underlying_order_priority,
	uo.link_to_creative_group AS underlying_order_link_to_creative_group,
	uo.destination_url AS underlying_order_destination_url,
	uo.utm_tag AS underlying_order_utm_tag,
	uo.created_at AS underlying_order_created_at,
	uo.updated_at AS underlying_order_updated_at,
	cg.id AS creative_group_id,
	cg.name AS creative_group_name,
	cg.approved AS creative_group_approved,
	cg.created_at AS creative_group_created_at,
	cg.updated_at AS creative_group_updated_at,
	bt.id AS board_type_id,
	bt.name AS board_type_name,
	bt.description AS board_type_description,
	bt.dimensions AS board_type_dimensions,
	bt.width AS board_type_width,
	bt.height AS board_type_height,
	bt.hourly_price AS board_type_hourly_price,
	u.id AS owner_id,
	u.name AS owner_name,
	u.email AS owner_email
FROM orders o
	JOIN ad_with_priority a ON a.order_id = o.id
	JOIN underlying_orders uo ON uo.id = a.underlying_order_id
	JOIN creative_groups cg ON cg.id = uo.link_to_creative_group
	LEFT JOIN board_types bt ON bt.id = a.board_type_id
	LEFT JOIN users u ON u.id = o.user_id
WHERE o.status = 'pending'
ORDER BY o.created_at DESC
`

type ListOrdersToApproveRow struct {
	OrderID                            pgtype.UUID
	OrderUserID                        pgtype.UUID
	OrderRequireAdminApproval          pgtype.Bool
	OrderStatus                        pgtype.Text
	OrderCreatedAt                     pgtype.Timestamptz
	OrderUpdatedAt                     pgtype.Timestamptz
	OrderCreditSpent                   pgtype.Numeric
	OrderTotalDollars                  pgtype.Numeric
	AdID                               pgtype.UUID
	AdUnderlyingOrderID                int32
	AdOrderID                          pgtype.UUID
	AdBoardTypeID                      int32
	AdAdMinutes                        int32
	AdTimeOfWeekRange                  []byte
	AdPriority                         pgtype.Int4
	AdCompletionSeconds                pgtype.Int4
	AdCreatedAt                        pgtype.Timestamptz
	AdUpdatedAt                        pgtype.Timestamptz
	UnderlyingOrderID                  int32
	UnderlyingOrderPriority            int32
	UnderlyingOrderLinkToCreativeGroup pgtype.Int4
	UnderlyingOrderDestinationUrl      pgtype.Text
	UnderlyingOrderUtmTag              pgtype.Text
	UnderlyingOrderCreatedAt           pgtype.Timestamptz
	UnderlyingOrderUpdatedAt           pgtype.Timestamptz
	CreativeGroupID                    int32
	CreativeGroupName                  string
	CreativeGroupApproved              pgtype.Bool
	CreativeGroupCreatedAt             pgtype.Timestamptz
	CreativeGroupUpdatedAt             pgtype.Timestamptz
	BoardTypeID                        pgtype.Int4
	BoardTypeName                      pgtype.Text
	BoardTypeDescription               pgtype.Text
	BoardTypeDimensions                pgtype.Text
	BoardTypeWidth                     pgtype.Int4
	BoardTypeHeight                    pgtype.Int4
	BoardTypeHourlyPrice               pgtype.Int4
	OwnerID                            pgtype.UUID
	OwnerName                          pgtype.Text
	OwnerEmail                         pgtype.Text
}

func (q *Queries) ListOrdersToApprove(ctx context.Context) ([]ListOrdersToApproveRow, error) {
	rows, err := q.db.Query(ctx, listOrdersToApprove)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrdersToApproveRow
	for rows.Next() {
		var i ListOrdersToApproveRow
		if err := rows.Scan(
			&i.OrderID,
			&i.OrderUserID,
			&i.OrderRequireAdminApproval,
			&i.OrderStatus,
			&i.OrderCreatedAt,
			&i.OrderUpdatedAt,
			&i.OrderCreditSpent,
			&i.OrderTotalDollars,
			&i.AdID,
			&i.AdUnderlyingOrderID,
			&i.AdOrderID,
			&i.AdBoardTypeID,
			&i.AdAdMinutes,
			&i.AdTimeOfWeekRange,
			&i.AdPriority,
			&i.AdCompletionSeconds,
			&i.AdCreatedAt,
			&i.AdUpdatedAt,
			&i.UnderlyingOrderID,
			&i.UnderlyingOrderPriority,
			&i.UnderlyingOrderLinkToCreativeGroup,
			&i.UnderlyingOrderDestinationUrl,
			&i.UnderlyingOrderUtmTag,
			&i.UnderlyingOrderCreatedAt,
			&i.UnderlyingOrderUpdatedAt,
			&i.CreativeGroupID,
			&i.CreativeGroupName,
			&i.CreativeGroupApproved,
			&i.CreativeGroupCreatedAt,
			&i.CreativeGroupUpdatedAt,
			&i.BoardTypeID,
			&i.BoardTypeName,
			&i.BoardTypeDescription,
			&i.BoardTypeDimensions,
			&i.BoardTypeWidth,
			&i.BoardTypeHeight,
			&i.BoardTypeHourlyPrice,
			&i.OwnerID,
			&i.OwnerName,
			&i.OwnerEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAdWithPriority = `-- name: UpdateAdWithPriority :one
UPDATE ad_with_priority
SET board_type_id = $2,
	ad_minutes = $3,
	time_of_week_range = $4::jsonb,
	priority = $5,
	updated_at = NOW()
WHERE id = $1
RETURNING id, underlying_order_id, order_id, board_type_id, ad_minutes, time_of_week_range, completion_seconds, priority, created_at, updated_at
`

type UpdateAdWithPriorityParams struct {
	ID          pgtype.UUID
	BoardTypeID int32
	AdMinutes   int32
	Column4     []byte
	Priority    pgtype.Int4
}

func (q *Queries) UpdateAdWithPriority(ctx context.Context, arg UpdateAdWithPriorityParams) (AdWithPriority, error) {
	row := q.db.QueryRow(ctx, updateAdWithPriority,
		arg.ID,
		arg.BoardTypeID,
		arg.AdMinutes,
		arg.Column4,
		arg.Priority,
	)
	var i AdWithPriority
	err := row.Scan(
		&i.ID,
		&i.UnderlyingOrderID,
		&i.OrderID,
		&i.BoardTypeID,
		&i.AdMinutes,
		&i.TimeOfWeekRange,
		&i.CompletionSeconds,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCreativeStatus = `-- name: UpdateCreativeStatus :one
UPDATE creatives
SET status = $2,
	updated_at = NOW()
WHERE id = $1
RETURNING id,
	creative_group_id,
	asset_link,
	type,
	status,
	date_added,
	created_at,
	updated_at
`

type UpdateCreativeStatusParams struct {
	ID     int32
	Status CreativeStatus
}

type UpdateCreativeStatusRow struct {
	ID              int32
	CreativeGroupID pgtype.Int4
	AssetLink       string
	Type            string
	Status          CreativeStatus
	DateAdded       pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) UpdateCreativeStatus(ctx context.Context, arg UpdateCreativeStatusParams) (UpdateCreativeStatusRow, error) {
	row := q.db.QueryRow(ctx, updateCreativeStatus, arg.ID, arg.Status)
	var i UpdateCreativeStatusRow
	err := row.Scan(
		&i.ID,
		&i.CreativeGroupID,
		&i.AssetLink,
		&i.Type,
		&i.Status,
		&i.DateAdded,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrderRequireAdminApproval = `-- name: UpdateOrderRequireAdminApproval :one
UPDATE orders
SET require_admin_approval = $2,
	status = $3,
	updated_at = NOW()
WHERE id = $1
RETURNING id,
	user_id,
	require_admin_approval,
	status,
	created_at,
	updated_at,
	credit_spent,
	total_dollars
`

type UpdateOrderRequireAdminApprovalParams struct {
	ID                   pgtype.UUID
	RequireAdminApproval pgtype.Bool
	Status               pgtype.Text
}

func (q *Queries) UpdateOrderRequireAdminApproval(ctx context.Context, arg UpdateOrderRequireAdminApprovalParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderRequireAdminApproval, arg.ID, arg.RequireAdminApproval, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RequireAdminApproval,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreditSpent,
		&i.TotalDollars,
	)
	return i, err
}

const updateOrderRequireAdminApprovalWithCredits = `-- name: UpdateOrderRequireAdminApprovalWithCredits :one
UPDATE orders
SET require_admin_approval = $2,
	status = $3,
	credit_spent = $4,
	total_dollars = $4,
	updated_at = NOW()
WHERE id = $1
RETURNING id,
	user_id,
	require_admin_approval,
	status,
	created_at,
	updated_at,
	credit_spent,
	total_dollars
`

type UpdateOrderRequireAdminApprovalWithCreditsParams struct {
	ID                   pgtype.UUID
	RequireAdminApproval pgtype.Bool
	Status               pgtype.Text
	CreditSpent          pgtype.Numeric
}

func (q *Queries) UpdateOrderRequireAdminApprovalWithCredits(ctx context.Context, arg UpdateOrderRequireAdminApprovalWithCreditsParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderRequireAdminApprovalWithCredits,
		arg.ID,
		arg.RequireAdminApproval,
		arg.Status,
		arg.CreditSpent,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RequireAdminApproval,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreditSpent,
		&i.TotalDollars,
	)
	return i, err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET status = $2,
	updated_at = NOW()
WHERE id = $1
RETURNING id,
	user_id,
	require_admin_approval,
	status,
	created_at,
	updated_at,
	credit_spent,
	total_dollars
`

type UpdateOrderStatusParams struct {
	ID     pgtype.UUID
	Status pgtype.Text
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus, arg.ID, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RequireAdminApproval,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreditSpent,
		&i.TotalDollars,
	)
	return i, err
}

const updateUnderlyingOrder = `-- name: UpdateUnderlyingOrder :one
UPDATE underlying_orders
SET priority = $2,
	destination_url = $3,
	utm_tag = $4,
	updated_at = NOW()
WHERE id = $1
RETURNING id, priority, link_to_creative_group, created_at, updated_at, destination_url, utm_tag
`

type UpdateUnderlyingOrderParams struct {
	ID             int32
	Priority       int32
	DestinationUrl pgtype.Text
	UtmTag         pgtype.Text
}

func (q *Queries) UpdateUnderlyingOrder(ctx context.Context, arg UpdateUnderlyingOrderParams) (UnderlyingOrder, error) {
	row := q.db.QueryRow(ctx, updateUnderlyingOrder,
		arg.ID,
		arg.Priority,
		arg.DestinationUrl,
		arg.UtmTag,
	)
	var i UnderlyingOrder
	err := row.Scan(
		&i.ID,
		&i.Priority,
		&i.LinkToCreativeGroup,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DestinationUrl,
		&i.UtmTag,
	)
	return i, err
}
