// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: play_logs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteOldPlayLogs = `-- name: DeleteOldPlayLogs :exec
DELETE FROM play_logs
WHERE played_at < $1
`

func (q *Queries) DeleteOldPlayLogs(ctx context.Context, playedAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteOldPlayLogs, playedAt)
	return err
}

const insertPlayLog = `-- name: InsertPlayLog :exec
INSERT INTO play_logs (content_type, content_id, duration_seconds, played_at)
VALUES ($1, $2, $3, NOW())
`

type InsertPlayLogParams struct {
	ContentType     string
	ContentID       string
	DurationSeconds int32
}

func (q *Queries) InsertPlayLog(ctx context.Context, arg InsertPlayLogParams) error {
	_, err := q.db.Exec(ctx, insertPlayLog, arg.ContentType, arg.ContentID, arg.DurationSeconds)
	return err
}
