// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: priority_configs.sql

package db

import (
	"context"
)

const getAdPriorityConfigByValue = `-- name: GetAdPriorityConfigByValue :one
SELECT value,
    name,
    description,
    location,
    multiplier,
    price_per_hour,
    price_label,
    type,
    sort_order
FROM ad_priority_config
WHERE value = $1
`

func (q *Queries) GetAdPriorityConfigByValue(ctx context.Context, value int32) (AdPriorityConfig, error) {
	row := q.db.QueryRow(ctx, getAdPriorityConfigByValue, value)
	var i AdPriorityConfig
	err := row.Scan(
		&i.Value,
		&i.Name,
		&i.Description,
		&i.Location,
		&i.Multiplier,
		&i.PricePerHour,
		&i.PriceLabel,
		&i.Type,
		&i.SortOrder,
	)
	return i, err
}

const getVendorAllocationPriorityConfigByValue = `-- name: GetVendorAllocationPriorityConfigByValue :one
SELECT value,
    name,
    description,
    allowed_roles,
    sort_order
FROM vendor_allocation_priority_config
WHERE value = $1
`

func (q *Queries) GetVendorAllocationPriorityConfigByValue(ctx context.Context, value int32) (VendorAllocationPriorityConfig, error) {
	row := q.db.QueryRow(ctx, getVendorAllocationPriorityConfigByValue, value)
	var i VendorAllocationPriorityConfig
	err := row.Scan(
		&i.Value,
		&i.Name,
		&i.Description,
		&i.AllowedRoles,
		&i.SortOrder,
	)
	return i, err
}

const listAdPriorityConfigs = `-- name: ListAdPriorityConfigs :many
SELECT value,
    name,
    description,
    location,
    multiplier,
    price_per_hour,
    price_label,
    type,
    sort_order
FROM ad_priority_config
ORDER BY sort_order, value
`

func (q *Queries) ListAdPriorityConfigs(ctx context.Context) ([]AdPriorityConfig, error) {
	rows, err := q.db.Query(ctx, listAdPriorityConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdPriorityConfig
	for rows.Next() {
		var i AdPriorityConfig
		if err := rows.Scan(
			&i.Value,
			&i.Name,
			&i.Description,
			&i.Location,
			&i.Multiplier,
			&i.PricePerHour,
			&i.PriceLabel,
			&i.Type,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVendorAllocationPriorityConfigsByRole = `-- name: ListVendorAllocationPriorityConfigsByRole :many
SELECT value,
    name,
    description,
    allowed_roles,
    sort_order
FROM vendor_allocation_priority_config
WHERE $1::text = ANY(allowed_roles)
ORDER BY sort_order, value
`

func (q *Queries) ListVendorAllocationPriorityConfigsByRole(ctx context.Context, dollar_1 string) ([]VendorAllocationPriorityConfig, error) {
	rows, err := q.db.Query(ctx, listVendorAllocationPriorityConfigsByRole, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VendorAllocationPriorityConfig
	for rows.Next() {
		var i VendorAllocationPriorityConfig
		if err := rows.Scan(
			&i.Value,
			&i.Name,
			&i.Description,
			&i.AllowedRoles,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
