// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: referrals.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const referralStatsByReferrerID = `-- name: ReferralStatsByReferrerID :one
SELECT COUNT(*)::int AS total_referrals,
    COUNT(*) FILTER (
        WHERE status = 'completed'
    )::int AS successful_referrals,
    COALESCE(SUM(credits_awarded), 0)::numeric AS credits_earned
FROM referrals
WHERE referrer_id = $1
`

type ReferralStatsByReferrerIDRow struct {
	TotalReferrals      int32
	SuccessfulReferrals int32
	CreditsEarned       pgtype.Numeric
}

func (q *Queries) ReferralStatsByReferrerID(ctx context.Context, referrerID pgtype.UUID) (ReferralStatsByReferrerIDRow, error) {
	row := q.db.QueryRow(ctx, referralStatsByReferrerID, referrerID)
	var i ReferralStatsByReferrerIDRow
	err := row.Scan(&i.TotalReferrals, &i.SuccessfulReferrals, &i.CreditsEarned)
	return i, err
}
