// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: sample.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, email, password_hash, role)
VALUES ($1, $2, $3, $4)
RETURNING id, name, email, email_verified, image, next_auth_id, stripe_customer_id, credits, role, created_at, updated_at, password_hash
`

type CreateUserParams struct {
	Name         pgtype.Text
	Email        string
	PasswordHash pgtype.Text
	Role         UserRole
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.NextAuthID,
		&i.StripeCustomerID,
		&i.Credits,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, name, email, email_verified, image, next_auth_id, stripe_customer_id, credits, role, created_at, updated_at, password_hash
FROM users
WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.NextAuthID,
		&i.StripeCustomerID,
		&i.Credits,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
	)
	return i, err
}

const getUserStats = `-- name: GetUserStats :one
SELECT u.credits,
	COUNT(orders.id) AS pending_orders
FROM users u
	LEFT JOIN orders ON u.id = orders.user_id
	AND orders.status = 'pending'
WHERE u.id = $1
GROUP BY u.credits
`

type GetUserStatsRow struct {
	Credits       pgtype.Numeric
	PendingOrders int64
}

func (q *Queries) GetUserStats(ctx context.Context, id pgtype.UUID) (GetUserStatsRow, error) {
	row := q.db.QueryRow(ctx, getUserStats, id)
	var i GetUserStatsRow
	err := row.Scan(&i.Credits, &i.PendingOrders)
	return i, err
}

const getUserStatsWithSpend = `-- name: GetUserStatsWithSpend :one
SELECT u.credits,
	COALESCE(SUM(o.credit_spent), 0)::numeric AS lifetime_credit_spend,
	COALESCE(SUM(o.total_dollars), 0)::numeric AS lifetime_dollar_spend,
	COUNT(o.id) FILTER (
		WHERE o.status IN ('pending', 'active')
	)::bigint AS active_orders,
	COUNT(o.id) FILTER (
		WHERE o.status = 'completed'
	)::bigint AS completed_orders,
	COUNT(o.id) FILTER (
		WHERE o.status = 'cancelled'
	)::bigint AS cancelled_orders
FROM users u
	LEFT JOIN orders o ON o.user_id = u.id
WHERE u.id = $1
GROUP BY u.id,
	u.credits
`

type GetUserStatsWithSpendRow struct {
	Credits             pgtype.Numeric
	LifetimeCreditSpend pgtype.Numeric
	LifetimeDollarSpend pgtype.Numeric
	ActiveOrders        int64
	CompletedOrders     int64
	CancelledOrders     int64
}

func (q *Queries) GetUserStatsWithSpend(ctx context.Context, id pgtype.UUID) (GetUserStatsWithSpendRow, error) {
	row := q.db.QueryRow(ctx, getUserStatsWithSpend, id)
	var i GetUserStatsWithSpendRow
	err := row.Scan(
		&i.Credits,
		&i.LifetimeCreditSpend,
		&i.LifetimeDollarSpend,
		&i.ActiveOrders,
		&i.CompletedOrders,
		&i.CancelledOrders,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, email, email_verified, image, next_auth_id, stripe_customer_id, credits, role, created_at, updated_at, password_hash
FROM users
ORDER BY created_at DESC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.EmailVerified,
			&i.Image,
			&i.NextAuthID,
			&i.StripeCustomerID,
			&i.Credits,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PasswordHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
