// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSessionWithUser = `-- name: GetSessionWithUser :one
SELECT u.id,
  u.role,
  s.expires
FROM sessions s
  JOIN users u ON s.user_id = u.id
WHERE s.session_token = $1
  AND s.expires > NOW()
`

type GetSessionWithUserRow struct {
	ID      pgtype.UUID
	Role    UserRole
	Expires pgtype.Timestamptz
}

func (q *Queries) GetSessionWithUser(ctx context.Context, sessionToken string) (GetSessionWithUserRow, error) {
	row := q.db.QueryRow(ctx, getSessionWithUser, sessionToken)
	var i GetSessionWithUserRow
	err := row.Scan(&i.ID, &i.Role, &i.Expires)
	return i, err
}
