// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addUserCredits = `-- name: AddUserCredits :one
UPDATE users
SET credits = credits + $1::numeric,
    updated_at = NOW()
WHERE id = $2
RETURNING id,
    name,
    email,
    email_verified,
    image,
    next_auth_id,
    stripe_customer_id,
    password_hash,
    credits,
    role,
    created_at,
    updated_at
`

type AddUserCreditsParams struct {
	Credits pgtype.Numeric
	ID      pgtype.UUID
}

type AddUserCreditsRow struct {
	ID               pgtype.UUID
	Name             pgtype.Text
	Email            string
	EmailVerified    pgtype.Timestamptz
	Image            pgtype.Text
	NextAuthID       pgtype.Text
	StripeCustomerID pgtype.Text
	PasswordHash     pgtype.Text
	Credits          pgtype.Numeric
	Role             UserRole
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) AddUserCredits(ctx context.Context, arg AddUserCreditsParams) (AddUserCreditsRow, error) {
	row := q.db.QueryRow(ctx, addUserCredits, arg.Credits, arg.ID)
	var i AddUserCreditsRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.NextAuthID,
		&i.StripeCustomerID,
		&i.PasswordHash,
		&i.Credits,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id,
    name,
    email,
    email_verified,
    image,
    next_auth_id,
    stripe_customer_id,
    password_hash,
    credits,
    role,
    created_at,
    updated_at
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID               pgtype.UUID
	Name             pgtype.Text
	Email            string
	EmailVerified    pgtype.Timestamptz
	Image            pgtype.Text
	NextAuthID       pgtype.Text
	StripeCustomerID pgtype.Text
	PasswordHash     pgtype.Text
	Credits          pgtype.Numeric
	Role             UserRole
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.NextAuthID,
		&i.StripeCustomerID,
		&i.PasswordHash,
		&i.Credits,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id,
    name,
    email,
    email_verified,
    image,
    next_auth_id,
    stripe_customer_id,
    password_hash,
    credits,
    role,
    created_at,
    updated_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID               pgtype.UUID
	Name             pgtype.Text
	Email            string
	EmailVerified    pgtype.Timestamptz
	Image            pgtype.Text
	NextAuthID       pgtype.Text
	StripeCustomerID pgtype.Text
	PasswordHash     pgtype.Text
	Credits          pgtype.Numeric
	Role             UserRole
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.NextAuthID,
		&i.StripeCustomerID,
		&i.PasswordHash,
		&i.Credits,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserByID = `-- name: UpdateUserByID :one
UPDATE users
SET name = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id,
    name,
    email,
    email_verified,
    image,
    next_auth_id,
    stripe_customer_id,
    password_hash,
    credits,
    role,
    created_at,
    updated_at
`

type UpdateUserByIDParams struct {
	ID   pgtype.UUID
	Name pgtype.Text
}

type UpdateUserByIDRow struct {
	ID               pgtype.UUID
	Name             pgtype.Text
	Email            string
	EmailVerified    pgtype.Timestamptz
	Image            pgtype.Text
	NextAuthID       pgtype.Text
	StripeCustomerID pgtype.Text
	PasswordHash     pgtype.Text
	Credits          pgtype.Numeric
	Role             UserRole
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) UpdateUserByID(ctx context.Context, arg UpdateUserByIDParams) (UpdateUserByIDRow, error) {
	row := q.db.QueryRow(ctx, updateUserByID, arg.ID, arg.Name)
	var i UpdateUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.NextAuthID,
		&i.StripeCustomerID,
		&i.PasswordHash,
		&i.Credits,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
