// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: vendor_allocations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVendorAllocation = `-- name: CreateVendorAllocation :one
INSERT INTO vendor_allocations (
        user_id,
        underlying_order_id,
        priority,
        recurring,
        time_to_show_mode,
        times_of_week,
        percentage,
        specific_dates,
        board_ids,
        require_admin_approval
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10
    )
RETURNING id, user_id, underlying_order_id, priority, recurring, board_ids, require_admin_approval, created_at, updated_at, time_to_show_mode, times_of_week, percentage, specific_dates
`

type CreateVendorAllocationParams struct {
	UserID               pgtype.UUID
	UnderlyingOrderID    int32
	Priority             int32
	Recurring            pgtype.Bool
	TimeToShowMode       string
	TimesOfWeek          []byte
	Percentage           pgtype.Int4
	SpecificDates        []pgtype.Date
	BoardIds             []string
	RequireAdminApproval pgtype.Bool
}

// Note: underlying_order_id is always provided by backend (auto-created from uploaded files).
// Geography is stored on underlying_order via geo_features, not on vendor_allocations.
func (q *Queries) CreateVendorAllocation(ctx context.Context, arg CreateVendorAllocationParams) (VendorAllocation, error) {
	row := q.db.QueryRow(ctx, createVendorAllocation,
		arg.UserID,
		arg.UnderlyingOrderID,
		arg.Priority,
		arg.Recurring,
		arg.TimeToShowMode,
		arg.TimesOfWeek,
		arg.Percentage,
		arg.SpecificDates,
		arg.BoardIds,
		arg.RequireAdminApproval,
	)
	var i VendorAllocation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UnderlyingOrderID,
		&i.Priority,
		&i.Recurring,
		&i.BoardIds,
		&i.RequireAdminApproval,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TimeToShowMode,
		&i.TimesOfWeek,
		&i.Percentage,
		&i.SpecificDates,
	)
	return i, err
}

const deleteVendorAllocation = `-- name: DeleteVendorAllocation :exec
DELETE FROM vendor_allocations
WHERE id = $1
`

func (q *Queries) DeleteVendorAllocation(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteVendorAllocation, id)
	return err
}

const getCreativeGroupForVendorAllocation = `-- name: GetCreativeGroupForVendorAllocation :one
SELECT cg.id,
    cg.name,
    cg.approved,
    cg.created_at,
    cg.updated_at
FROM vendor_allocations va
    JOIN underlying_orders uo ON va.underlying_order_id = uo.id
    JOIN creative_groups cg ON uo.link_to_creative_group = cg.id
WHERE va.id = $1
`

// Get the creative group for a vendor allocation via: VendorAllocation -> UnderlyingOrder -> CreativeGroup
func (q *Queries) GetCreativeGroupForVendorAllocation(ctx context.Context, id pgtype.UUID) (CreativeGroup, error) {
	row := q.db.QueryRow(ctx, getCreativeGroupForVendorAllocation, id)
	var i CreativeGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Approved,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCreativesForVendorAllocation = `-- name: GetCreativesForVendorAllocation :many
SELECT c.id,
    c.creative_group_id,
    c.asset_link,
    c.type,
    c.status,
    c.date_added,
    c.created_at,
    c.updated_at,
    cg.id as creative_group_id_full,
    cg.name as creative_group_name,
    cg.approved as creative_group_approved
FROM vendor_allocations va
    JOIN underlying_orders uo ON va.underlying_order_id = uo.id
    JOIN creative_groups cg ON uo.link_to_creative_group = cg.id
    JOIN creatives c ON c.creative_group_id = cg.id
WHERE va.id = $1
ORDER BY c.created_at ASC
`

type GetCreativesForVendorAllocationRow struct {
	ID                    int32
	CreativeGroupID       pgtype.Int4
	AssetLink             string
	Type                  string
	Status                CreativeStatus
	DateAdded             pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	CreativeGroupIDFull   int32
	CreativeGroupName     string
	CreativeGroupApproved pgtype.Bool
}

// Get all creatives for a vendor allocation via: VendorAllocation -> UnderlyingOrder -> CreativeGroup -> Creatives
func (q *Queries) GetCreativesForVendorAllocation(ctx context.Context, id pgtype.UUID) ([]GetCreativesForVendorAllocationRow, error) {
	rows, err := q.db.Query(ctx, getCreativesForVendorAllocation, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCreativesForVendorAllocationRow
	for rows.Next() {
		var i GetCreativesForVendorAllocationRow
		if err := rows.Scan(
			&i.ID,
			&i.CreativeGroupID,
			&i.AssetLink,
			&i.Type,
			&i.Status,
			&i.DateAdded,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreativeGroupIDFull,
			&i.CreativeGroupName,
			&i.CreativeGroupApproved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVendorAllocationByID = `-- name: GetVendorAllocationByID :one
SELECT id,
    user_id,
    underlying_order_id,
    priority,
    recurring,
    time_to_show_mode,
    times_of_week,
    percentage,
    specific_dates,
    board_ids,
    require_admin_approval,
    created_at,
    updated_at
FROM vendor_allocations
WHERE id = $1
`

type GetVendorAllocationByIDRow struct {
	ID                   pgtype.UUID
	UserID               pgtype.UUID
	UnderlyingOrderID    int32
	Priority             int32
	Recurring            pgtype.Bool
	TimeToShowMode       string
	TimesOfWeek          []byte
	Percentage           pgtype.Int4
	SpecificDates        []pgtype.Date
	BoardIds             []string
	RequireAdminApproval pgtype.Bool
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

func (q *Queries) GetVendorAllocationByID(ctx context.Context, id pgtype.UUID) (GetVendorAllocationByIDRow, error) {
	row := q.db.QueryRow(ctx, getVendorAllocationByID, id)
	var i GetVendorAllocationByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UnderlyingOrderID,
		&i.Priority,
		&i.Recurring,
		&i.TimeToShowMode,
		&i.TimesOfWeek,
		&i.Percentage,
		&i.SpecificDates,
		&i.BoardIds,
		&i.RequireAdminApproval,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBoardsByOwnerID = `-- name: ListBoardsByOwnerID :many
SELECT b.id,
    b.board_type_id,
    b.owner_id,
    b.device_id,
    b.approved,
    b.location,
    b.created_at,
    b.updated_at,
    bt.name as board_type_name
FROM boards b
    LEFT JOIN board_types bt ON b.board_type_id = bt.id
WHERE b.owner_id = $1
ORDER BY b.created_at DESC
`

type ListBoardsByOwnerIDRow struct {
	ID            pgtype.UUID
	BoardTypeID   pgtype.Int4
	OwnerID       pgtype.UUID
	DeviceID      pgtype.Text
	Approved      pgtype.Bool
	Location      pgtype.Text
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	BoardTypeName pgtype.Text
}

func (q *Queries) ListBoardsByOwnerID(ctx context.Context, ownerID pgtype.UUID) ([]ListBoardsByOwnerIDRow, error) {
	rows, err := q.db.Query(ctx, listBoardsByOwnerID, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBoardsByOwnerIDRow
	for rows.Next() {
		var i ListBoardsByOwnerIDRow
		if err := rows.Scan(
			&i.ID,
			&i.BoardTypeID,
			&i.OwnerID,
			&i.DeviceID,
			&i.Approved,
			&i.Location,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BoardTypeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVendorAllocationsByUserID = `-- name: ListVendorAllocationsByUserID :many
SELECT id,
    user_id,
    underlying_order_id,
    priority,
    recurring,
    time_to_show_mode,
    times_of_week,
    percentage,
    specific_dates,
    board_ids,
    require_admin_approval,
    created_at,
    updated_at
FROM vendor_allocations
WHERE user_id = $1
ORDER BY created_at DESC
`

type ListVendorAllocationsByUserIDRow struct {
	ID                   pgtype.UUID
	UserID               pgtype.UUID
	UnderlyingOrderID    int32
	Priority             int32
	Recurring            pgtype.Bool
	TimeToShowMode       string
	TimesOfWeek          []byte
	Percentage           pgtype.Int4
	SpecificDates        []pgtype.Date
	BoardIds             []string
	RequireAdminApproval pgtype.Bool
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

func (q *Queries) ListVendorAllocationsByUserID(ctx context.Context, userID pgtype.UUID) ([]ListVendorAllocationsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listVendorAllocationsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVendorAllocationsByUserIDRow
	for rows.Next() {
		var i ListVendorAllocationsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UnderlyingOrderID,
			&i.Priority,
			&i.Recurring,
			&i.TimeToShowMode,
			&i.TimesOfWeek,
			&i.Percentage,
			&i.SpecificDates,
			&i.BoardIds,
			&i.RequireAdminApproval,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVendorAllocation = `-- name: UpdateVendorAllocation :one
UPDATE vendor_allocations
SET underlying_order_id = CASE
        WHEN $2::integer IS NULL THEN underlying_order_id
        ELSE $2
    END,
    priority = COALESCE($3, priority),
    recurring = COALESCE($4, recurring),
    time_to_show_mode = COALESCE($5, time_to_show_mode),
    times_of_week = CASE
        WHEN $6::jsonb IS NULL THEN times_of_week
        ELSE $6
    END,
    percentage = COALESCE($7, percentage),
    specific_dates = COALESCE($8, specific_dates),
    board_ids = COALESCE($9, board_ids),
    require_admin_approval = COALESCE($10, require_admin_approval),
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, underlying_order_id, priority, recurring, board_ids, require_admin_approval, created_at, updated_at, time_to_show_mode, times_of_week, percentage, specific_dates
`

type UpdateVendorAllocationParams struct {
	ID                   pgtype.UUID
	Column2              int32
	Priority             int32
	Recurring            pgtype.Bool
	TimeToShowMode       string
	Column6              []byte
	Percentage           pgtype.Int4
	SpecificDates        []pgtype.Date
	BoardIds             []string
	RequireAdminApproval pgtype.Bool
}

func (q *Queries) UpdateVendorAllocation(ctx context.Context, arg UpdateVendorAllocationParams) (VendorAllocation, error) {
	row := q.db.QueryRow(ctx, updateVendorAllocation,
		arg.ID,
		arg.Column2,
		arg.Priority,
		arg.Recurring,
		arg.TimeToShowMode,
		arg.Column6,
		arg.Percentage,
		arg.SpecificDates,
		arg.BoardIds,
		arg.RequireAdminApproval,
	)
	var i VendorAllocation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UnderlyingOrderID,
		&i.Priority,
		&i.Recurring,
		&i.BoardIds,
		&i.RequireAdminApproval,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TimeToShowMode,
		&i.TimesOfWeek,
		&i.Percentage,
		&i.SpecificDates,
	)
	return i, err
}
